export default [
  { nome: "A. Raymond Brasil Ltda." },
  { nome: "A.C.M.W. Indústria e Comércio Ltda." },
  { nome: "Aam Do Brasil" },
  { nome: "Ábaco Comércio E Locação De Equipamentos S/A" },
  { nome: "Abb Medição De Água S/A." },
  { nome: "Abc Industria E Comercio S.A." },
  { nome: "Ac Metalúrgica Ltda." },
  { nome: "Ace Schmersal Eletroeletrônica Ind. Ltda." },
  { nome: "Aco Verde Do Brasil S.A." },
  { nome: "Aços Vic Ltda." },
  { nome: "Aços Villares S/A" },
  { nome: "Açotecnica S/A. Ind. E Comércio" },
  { nome: "Acr Componentes Eletrônicos Ltda." },
  { nome: "Acr Conexões Ind. E Com Ltda." },
  { nome: "Acumuladores Moura S/A" },
  { nome: "Adidem Ind. Metalúrgica Ltda." },
  { nome: "Adidwm Ind. Metalúrgica Ltda." },
  { nome: "Aeroquip Do Brasil S/A" },
  { nome: "Agco Do Brasil Com. E Ind. Ltda." },
  { nome: "Agomolas Industria E Comércio Ltda." },
  { nome: "Agrale S/A" },
  { nome: "Agropaulo Agroindústria S.A - Messejana" },
  { nome: "Agrostahl S/A Industria E Comércio" },
  { nome: "Aisin Automotive Ltda." },
  { nome: "Aisin Do Brasil Com. E Ind. Ltda." },
  { nome: "Albany International Tecidos Técnicos Ltda." },
  { nome: "Alfredo Fantini Ind. E Com. Ltda." },
  { nome: "Allevard Molas Do Brasil Ltda." },
  { nome: "Alujet Comercial E Industrial Ltda." },
  { nome: "Alumec Ind. E Com. Ltda." },
  { nome: "Alunorte Produtos Metalúrgicos Ltda. - Epp" },
  { nome: "Alusur Do Brasil Ltda." },
  { nome: "Amino Química Ltda." },
  { nome: "Andreia Aparecida Costa Silva" },
  { nome: "Anglo Indústria E Comercio De Metais Ltda." },
  { nome: "Anicuns S/A Alcool E Derivados" },
  { nome: "Apatex Impregnadora De Papeis E Tecidos Ltda." },
  { nome: "Apis Delta Ltda." },
  { nome: "Arcelormittal Gonvarri Brasil - Produtos Siderúgicos S/A" },
  { nome: "Argus - Ignazio Sidoti Me" },
  { nome: "Arim Componentes S/A" },
  { nome: "Arlington Thermal Management - Pecas Automotivas Termofixas Ltda." },
  { nome: "Arnaldo Pollone Ind. E Com. Ltda." },
  { nome: "Arniflex Ind. E Com. De Artefatos De Borracha Ltda." },
  { nome: "Aro Estamparia E Ferramentaria Mecanica Ltda." },
  { nome: "Arosuco S/A" },
  { nome: "Arotubi Metais Ltda." },
  { nome: "Artama Industrial Ltda." },
  { nome: "As Brasil S/A" },
  { nome: "Asa Alumínio S/A." },
  { nome: "Asa Ind. E Com. S/A." },
  { nome: "Ask Crios Produtos Quimicos Do Brasil S.A." },
  { nome: "Audilab Ltda." },
  { nome: "Aunde Coplatex Do Brasil" },
  { nome: "Auto Forjas Ltda." },
  { nome: "Autocam Do Brasil Usinagem Ltda." },
  { nome: "Autocom Compon.Autom.Do Brasil Ltda." },
  { nome: "Autoliv Do Brasil Ltda." },
  { nome: "Autometal S.A" },
  { nome: "Autosplice Indústria E Comércio Ltda." },
  { nome: "Autotex Ind. E Com. Têxtil Ltda." },
  { nome: "Avibras Divisão Aérea E Naval S/A." },
  { nome: "Avs Brasil Getoflex Ltda. - Fabrica I" },
  { nome: "Axe Industrial Ltda." },
  { nome: "Axmol Industrial Ltda." },
  { nome: "Baerlocher Do Brasil S/A." },
  { nome: "Bann Química" },
  { nome: "Bantec Art Couros Ltda." },
  { nome: "Barlocher Do Brasil S/A." },
  { nome: "Basell Poliolefinas Ltda." },
  { nome: "Basso Componentes Automotivos Ltda." },
  { nome: "Bastien Comercial Ltda." },
  { nome: "Behr Brasil" },
  { nome: "Belenus Do Brasil Ltda." },
  { nome: "Belgo Bekaert Arames Ltda." },
  { nome: "Belgo Bekaert Art. De Arame Ltda." },
  { nome: "Belgo Bekaert Nordeste S/A" },
  { nome: "Bells Indústria E Comércio De Plástico E Metais Ltda. " },
  { nome: "Bematech Ind. E Com. De Equipamentos Eletrônicos S.A." },
  { nome: "Benteler Sistemas Automotivos Ltda." },
  { nome: "Bertin Ltda." },
  { nome: "Bf Produtos Alimentícios Ltda." },
  { nome: "Bimara Industria E Comercio De Produtos Plasticos Ltda." },
  { nome: "Bl Indústria Ótica Ltda." },
  { nome: "Bleistahl Brasil Metalurgia S.A" },
  { nome: "Blitz Ind. E Com De Plásticos" },
  { nome: "Bma Borrachas Monte Alto Ltda." },
  { nome: "Bollhoff Neumayer Industrial Ltda." },
  { nome: "Bonatti Aluminum" },
  { nome: "Bordoplas Brasil Ltda." },
  { nome: "Borg Warner Brasil Ltda." },
  { nome: "Borkar Tapetes Automotivos" },
  { nome: "Borlem Alumínio S.A." },
  { nome: "Borlem S/A. " },
  { nome: "Br Metals Fundições Ltda." },
  { nome: "Brandl Do Brasil Ltda." },
  { nome: "Brascabos Componentes Ltda." },
  { nome: "Brasimet Comércio E Indústria S/A." },
  { nome: "Braskem S/A" },
  { nome: "Brawal Ferramentaria De Precisão Ltda." },
  { nome: "Brf - Brasil Foods S/A" },
  { nome: "Bridgestone Do Brasil Industrial E Comércio Ltda." },
  { nome: "Bridgestone Firestone Brasil Ind. E Com. Ltda." },
  { nome: "Britania Eletrodomesticos S/A" },
  { nome: "Bs Ind E Com De Produtos Metalurgicos Eireli" },
  { nome: "Budai Indústria Metalúrgica Ltda." },
  { nome: "Bunge Fertilizantes S.A" },
  { nome: "Buschle & Lepper Sa" },
  { nome: "Cabfer Ferr. Usinagem Caldeiraria Ltda." },
  { nome: "Cabovel Industria E Comercio Ltda." },
  { nome: "Cadbury Adams Ind. E Com. De Produtos Alimentícios Ltda." },
  { nome: "Calibracom Controle De Processos Industriais Ltda. - Epp" },
  { nome: "Caoa Chery Automóveis Ltda." },
  { nome: "Caraíba Metais S/A" },
  { nome: "Carbono Lorena Ltda." },
  { nome: "Cardinal Health Brasil 402 Ltda." },
  { nome: "Cargill Agrícola Sa" },
  { nome: "Cargill Specialties" },
  { nome: "Casa Da Moeda Do Brasil" },
  { nome: "Casadoce Ind. E Com. Alimentos Ltda." },
  { nome: "Cascajú Agroindustrial S/A" },
  { nome: "Casco Do Brasil Ltda." },
  { nome: "Casp S/A Industria E Comercio" },
  { nome: "Caterpillar Brasil Ltda." },
  { nome: "Cba - Companhia Brasileira De Alumínio" },
  { nome: "Cce Da Amazônia S/A." },
  { nome: "Cecil S/A Laminacao De Metais" },
  { nome: "Cefet- R.J." },
  { nome: "Cellier Alimentos Do Brasil Ltda." },
  { nome: "Celulose Nipo Brasileira S/A - Cenibra" },
  { nome: "Cennabras Ind. E Com. Ltda." },
  { nome: "Central De Produção Do Galeão-Bagl" },
  { nome: "Cestari Industrial E Comercial S.A" },
  { nome: "Cge - Soc.Fab.De Peças Plásticas" },
  { nome: "Chematall Do Brasil Ltda." },
  { nome: "Chemtura Industria Quimica Do Brasil Ltda." },
  { nome: "Chris Cintos De Segurança Ltda." },
  { nome: "Cia De Cimentos Do Brasil" },
  { nome: "Cia Siderurgica Belgo-Mineira" },
  { nome: "Cia. De Ferro Ligas Da Bahia - Ferbasa" },
  { nome: "Cia. Ind. Vidros Ltda." },
  { nome: "Cia. Mogi De Café Solúvel" },
  { nome: "Cimaf Cabos S.A" },
  { nome: "Cinbal - Incoflandres Ind. E Com. De Flandres Ltda. (Matriz)" },
  { nome: "Cipatex Impregnadora De Papéis E Tecidos Ltda." },
  { nome: "Ciplan - Cimento Planalto S.A." },
  { nome: "Cisper Da Amazônia S/A" },
  { nome: "Click Automotiva Industrial Ltda." },
  { nome: "Cliptech Industria E Comercio Ltda." },
  { nome: "Cnh Latin America Ltda." },
  { nome: "Coats Corrente Ltda." },
  { nome: "Cobra Metais Decorativos Ltda." },
  { nome: "Cocam Cia De Café Solúvel E Derivados" },
  { nome: "Colabene Ind. E Com De Colas Ltda." },
  { nome: "Colauto Adesivos E Massas Ltda." },
  { nome: "Colbras Ind. E Com. Ltda." },
  { nome: "Columbian Chemicals Brasil Ltda." },
  { nome: "Comp Ind. E Com. De Metais E Madeiras Ltda." },
  { nome: "Comp Indústria E Comércio De Metais Ltda." },
  { nome: "Companhia De Cimentos Do Brasil" },
  { nome: "Companhia Siderúrgica De Tubarão" },
  { nome: "Companhia Siderúrgica Nacional" },
  { nome: "Componel Indústria E Comércio Ltda." },
  { nome: "Component Ind. E Com. Ltda." },
  { nome: "Conbrás Eletrometalúrgica Ltda." },
  { nome: "Concentrado Indústria De Produtos Lácteos Ltda. " },
  { nome: "Conformetal Estamparia De Metais Eireli" },
  { nome: "Continental Automotive Do Brasil Ltda." },
  { nome: "Continental Do Brasil Produtos Automotivos Ltda." },
  { nome: "Cooperativa Tritícola De Espumoso Ltda. - Cotriel" },
  { nome: "Copam - Comp. De Papelão E Madeira Ltda. " },
  { nome: "Copep Indústria E Comércio De Peças De Precisão Ltda." },
  { nome: "Coplac Do Brasil Ltda." },
  { nome: "Coplatex Do Brasil S/A" },
  { nome: "Coplatex Ind. E Com. De Tecidos Ltda." },
  { nome: "Corneta Ltda." },
  { nome: "Correias Mercúrio S.A. Ind. Com." },
  { nome: "Cosma Do Brasil Produtos E Servicos Automotivos Ltda." },
  { nome: "Cosmosplast Ind. E Com. De Plásticos" },
  { nome: "Cpp Industria E Comercio De Produtos Cardio - Pulmonares" },
  { nome: "Cpq Brasil Sa" },
  { nome: "Crisflex Produtos Técnicos De Borracha Ltda." },
  { nome: "Crw Ind.Com. De Plásticos Ltda." },
  { nome: "Cuno Latina Ltda." },
  { nome: "Daisan Usinagem Ltda." },
  { nome: "Dama Pel Com Distribuição De Papeis Ltd" },
  { nome: "Dambroz S.A Ind Mecânica E Metalúrgica" },
  { nome: "Dana Industrias Ltda." },
  { nome: "Dana Industrias Ltda. - Spicer Eixos Pesados" },
  { nome: "Danone Ltda." },
  { nome: "Dautec Industria E Comércio Ltda." },
  { nome: "Debony Usinagem De Precisão Ltda. " },
  { nome: "Delmac Do Brasil Ltda." },
  { nome: "Delphi Automotive Systems Ltda." },
  { nome: "Delphia Produtos Elétricos Ltda." },
  { nome: "Deluma Ind. E Com Ltda." },
  { nome: "Deluma Ind. E Com. Ltda." },
  { nome: "Denso Sistemas Térmicos Do Brasil Ltda." },
  { nome: "Dental Morelli Ltda." },
  { nome: "Dia-Frag Ind. E Com. Motopeças Ltda." },
  { nome: "Diatom Mineração Ltda." },
  { nome: "Dikas Da Vovó Alimentos Ltda. Epp" },
  { nome: "Dinaflex Ind De Artefatos De Borracha Ltda." },
  { nome: "Dini Textil Industria E Comercio Ltda." },
  { nome: "Dinicar Ind. Com. E Repres. Ltda." },
  { nome: "Domoral Ind. Metalúrgica Ltda." },
  { nome: "Dorma Sistemas De Controles Para Portas Ltda." },
  { nome: "Dormer Tools S/A" },
  {
    nome: "Dr. D. Muller Do Brasil Indústria E Comércio De Isolantes Elétricos Ltda.",
  },
  { nome: "Drava Metais Ltda." },
  { nome: "Dumontec Industrial E Comercial Ltda." },
  { nome: "Dura Automotive Systems Do Brasil" },
  { nome: "Durametal S/A." },
  { nome: "Duratex Comercial Exportadora S/A" },
  { nome: "Duratex Div. Deca" },
  { nome: "Duratex S.A. " },
  { nome: "Dutra’s Quality Ltda." },
  { nome: "Dvp Produtos Químicos" },
  { nome: "Dynaplast Ind. Ltda." },
  { nome: "Eaton Ltda." },
  { nome: "Eaton Ltda. - Divisão Transmissores" },
  { nome: "Ebara Ind. Mecânicas E Comércio Ltda." },
  { nome: "Ebf - Vaz Industria E Comércio Ltda." },
  { nome: "Edwardas Lifesciences Macchi Ltda." },
  { nome: "Efrani Ind.E Com.De Auto Peças Ltda." },
  { nome: "Efrari" },
  { nome: "Elasfil Do Brasil Ltda." },
  { nome: "Elastotec Artefatos De Borracha" },
  { nome: "Eldorado Indústrias Plásticas Ltda." },
  { nome: "Electrocast Ind. E Com. Ltda." },
  { nome: "Electrolux Da Amazonia Ltda." },
  { nome: "Electrolux Do Brasil S/A" },
  { nome: "Eletromecânica Dyna S/A" },
  { nome: "Eli Lilly Do Brasil Ltda." },
  { nome: "Elken Participações Ind. E Com. Ltda." },
  { nome: "Elring Klinger Do Brasil Ltda." },
  { nome: "Elster Medição De Água S/A" },
  { nome: "Eluma Sa Industria E Comercio" },
  { nome: "Emsar Brasil Ltda." },
  { nome: "Engemet Metalúrgica E Comércio Ltda." },
  { nome: "Engimplan Engenharia De Implante Ind. Com. Ltda." },
  { nome: "Ensinger Ind. Plast. Tecn. Ltda." },
  { nome: "Epd - Ind. E Com. De Produtos De Engenharia Ltda." },
  { nome: "Esmaltec S/A" },
  { nome: "Espas Brasil Desenvolvimento Automotivo Ltda." },
  { nome: "Espumacar Ind. E Com. Ltda." },
  { nome: "Espumatec Inj. Ind. Com. Ltda." },
  { nome: "Estamparia E Artefatos De Arames Mz Ltda." },
  { nome: "Etecon Usinagem Ltda. Epp" },
  { nome: "Eucatex S/A. Ind. E Comércio" },
  { nome: "Euro-Matic - Globalpack" },
  { nome: "Evolve Importacao E Comercio De Produtos Medicos E " },
  { nome: "F.B.A - Fundição Brasileira De Alumínio Ltda." },
  { nome: "F.C.C. Do Brasil Ltda." },
  { nome: "Fabinject Ind.Pl Stica Ltda." },
  { nome: "Fabramatic - Industria Metalúrgica Ltda." },
  { nome: "Fábrica De Celulose E Papel Da Amazônia S/A." },
  { nome: "Fábrica De Máquinas E Equipamentos Fameq Ltda." },
  { nome: "Fábrica Nacional De Chavetas Ltda." },
  { nome: "Fac. Economia, Administração E Contabilidade De Rb - Usp" },
  { nome: "Fae - Ferragens E Aparelhos Elétricos S/A." },
  { nome: "Faesa" },
  { nome: "Fagerdala Brasil Ltda." },
  { nome: "Fagor Ederlan Brasileira Auto Peças Ltda." },
  { nome: "Fagor Fundição Brasileira S/A" },
  { nome: "Fanaupe S.A. Fab. Nacional De Auto Peças" },
  { nome: "Fania - Fabrica Nacional De Instrumentos Para Autos" },
  { nome: "Fap Ind. Metal. Produtos Automotivos Ltda." },
  { nome: "Fastplas Automotive Ltda." },
  { nome: "Fastplas Automotive Ltda. (Mg)" },
  { nome: "Fe Fundição De Metais S/A" },
  { nome: "Federal Mogul Electrical Do Brasil Ltda." },
  { nome: "Feeder Industrial Ltda." },
  { nome: "Ferplast Pcs. Plast. Ferr. Ltda." },
  { nome: "Ferramentaria Jn Ltda." },
  { nome: "Ferteck Comercio De Plástico Ltda." },
  { nome: "Fertilizantes Heringer S.A" },
  { nome: "Fiat Automóveis S.A" },
  { nome: "Fibrasa Sudeste Ltda." },
  { nome: "Ficosa Retrovisores Do Brasil Ltda." },
  { nome: "Fix Press Usinagem Ltda. Epp" },
  { nome: "Fluid System Do Brasil Sa" },
  { nome: "Focus Tecnologia Em Plásticos S/A" },
  { nome: "Ford Brasil Ltda." },
  { nome: "Forjas Brasileiras S.A" },
  { nome: "Forjasul Eletrik S.A" },
  { nome: "Formparts Industria Metalurgica Eireli" },
  { nome: "Formtap Ind. E Com. S.A" },
  { nome: "Forte Indústria E Comércio De Artefatos Plásticos Ltda." },
  { nome: "Foseco Industrial E Comercial Ltda." },
  { nome: "Fractal Engenharia E Sistemas S.A" },
  { nome: "Freios Controil Ltda." },
  { nome: "Freudenberg Não-Tecidos Ltda. E Cia" },
  { nome: "Fte Indústria E Comércio Ltda." },
  { nome: "Fuchs Do Brasil S/A" },
  { nome: "Funcamp-Fundação De Desenvolvimento Da Unicamp" },
  { nome: "Fund. Centro De An. Pesq. E Inov.(Fucapi)" },
  { nome: "Fundação De Ciências Aplicadas - Unifei" },
  { nome: "Fundação Universidade Regional De Blumenau" },
  { nome: "Fundição Hubner Ltda." },
  { nome: "Fupresa S/A." },
  { nome: "G.M. Dos Reis Jr. Ind. Com. De Equips. Médicos" },
  { nome: "Gates Do Brasil Ind E Com Ltda." },
  { nome: "Gatsby Do Brasil Ltda." },
  { nome: "Geraldiscos Com. Ind. Repres. Cort. Ltda." },
  { nome: "Giesecke+Devrient Epayments Brasil Ltda." },
  { nome: "Girona Embalagens Industriais" },
  { nome: "Gisamar Ind. E Com. De Peças E Serviços De Torno Ltda." },
  { nome: "Gk&B Industria De Componentes" },
  { nome: "Gl Eletro Eletrônicos Ltda." },
  { nome: "Global Filters S.A" },
  { nome: "Gonçalves S/A Ind Gráfica" },
  { nome: "Goodyear Do Brasil Prod. De Borracha Ltda." },
  { nome: "Gráfica Rami Ltda." },
  { nome: "Grammer Do Brasil Ltda." },
  { nome: "Gt Do Brasil S/A. Ind E Com." },
  { nome: "Guarutor Usin. De Prec. Ltda." },
  { nome: "Gvs Do Brasil Ltda." },
  { nome: "Hba Hutchinson Brasil Automotive Ltda." },
  { nome: "H-Buster Do Brasil Comércio Ltda." },
  { nome: "Hcc, Inc" },
  { nome: "Helem System Automotive Ltda." },
  { nome: "Hendrix Ind. E Com. Ltda." },
  { nome: "Hengst Indústria De Filtros Ltda." },
  { nome: "Heraeus Electro-Nite" },
  { nome: "Heral S.A. Industria Metalúrgica" },
  { nome: "Hexagon Metrology Sistemas De Medição Ltda." },
  { nome: "Hisan Do Brasil Ltda." },
  { nome: "Homerplast Industria E Comércio De Plásticos Ltda." },
  { nome: "Honda Lock Sp Ind E Com Ltda." },
  { nome: "Houghton Brasil Ltda." },
  { nome: "Ht Micron Semicondutores Sa" },
  { nome: "Huber - Suhner" },
  { nome: "Huf Do Brasil Ltda." },
  { nome: "Huziteka Estamparia De Metais Ltda." },
  { nome: "Hyco Hidrover Ltda." },
  { nome: "Ibar-Ind. Bras. Art. Refratários S.A" },
  { nome: "Ibca Indústria Metalúrgica Ltda." },
  { nome: "Ideal Standard Wabco Ind.Com. Ltda." },
  { nome: "Ifer Estamparia E Ferramentaria" },
  { nome: "Iguaçu Celulose Papel S/A" },
  { nome: "Ilpea" },
  { nome: "Iluminação Automotiva Ltda." },
  { nome: "Imafix Ind. E Com De Peças Ltda." },
  { nome: "Imart - Marrara Tornearia De Peças Ltda." },
  { nome: "Impel Formigari Ind. Mec. De Peças E Equipamentos Ltda." },
  { nome: "Inbrac S.A Condutores Elétricos" },
  { nome: "Inbrasmec Indústria Mecânica Ltda." },
  { nome: "Inbrasp Ind. E Comércio De Plástico Ltda." },
  { nome: "Incaflex Indústria E Comércio Ltda." },
  { nome: "Incom Industrial Ltda." },
  { nome: "Ind Artef. De Bor. E Plast. Paranoa Ltda." },
  { nome: "Ind. De Artefatos De Alumínio Jangada Ltda." },
  { nome: "Indab Industria Metalúrgica Ltda." },
  { nome: "Indal - Indústria De Aços Laminados Ltda." },
  { nome: "Indaru Indústria E Comércio Ltda." },
  { nome: "Indebras Ind. Eletrom. Bras. Ltda." },
  { nome: "Inds. Gerais De Parafusos Ingepal Ltda." },
  { nome: "Industria De Fundição Tupy Ltda." },
  { nome: "Indústria De Laticinios Da Fazenda Ltda." },
  { nome: "Industria De Relógios Herweg S.A" },
  { nome: "Industria E Comercio De Laticínios Mercedes Ltda." },
  { nome: "Industria E Comercio Urso Branco Ltda." },
  { nome: "Indústria Eletro-Mecânica Elmebra Ltda." },
  { nome: "Indústria Marilia De Auto Peças S/A" },
  { nome: "Industria Mecânica J. Macedo Ltda." },
  { nome: "Industria Mecanica Samot Ltda." },
  { nome: "Industria Metalúrgica A. Pedro" },
  { nome: "Industria Metalúrgica Induspart Ltda. Me" },
  { nome: "Indústria Metalúrgica Mm Ltda." },
  { nome: "Indústria Metalúrgica Salmazo" },
  { nome: "Industria Nacional De Aços Laminados  Inal S/A" },
  { nome: "Industrial E Comercial Marvi Ltda." },
  { nome: "Industrial Levorin S/A" },
  { nome: "Industrias Mangotex Ltda." },
  { nome: "Injecom Ind E Com De Plásticos Ltda." },
  { nome: "Injepol" },
  { nome: "Innovatti  Ind. E Com. De Estéreis Sintéticos Ltda." },
  { nome: "Inpacom - Industria De Termoplásticos Ltda." },
  { nome: "Inser Indústria, Comércio E Serviço Ltda." },
  { nome: "Instituto Metodista De Ensino Superior" },
  { nome: "Intep Industria Plastica Ltda. Me" },
  { nome: "International Engines South America" },
  { nome: "Intier Automotive Closures Do Brasil Ltda." },
  { nome: "Inylbra Industria E Comercio Ltda." },
  { nome: "Inylbra Tapetes E Veludos Ltda." },
  { nome: "Iochpe Maxion S.A" },
  { nome: "Ipa - São Paulo Ind. E Comércio" },
  { nome: "Ipa Ind. Prod. Automotivos Rgs Ltda." },
  { nome: "Ipê Ind Com De Água Mineral E Refrigerantes Ltda. " },
  { nome: "Iramec Autopeças  S.A" },
  { nome: "Irmãos Parasmo S/A Ind. Mecânica" },
  { nome: "Isel Usinagem E Mecanica Em Geral Ltda." },
  { nome: "Italo Lanfredi S/A" },
  { nome: "Italspeed Automotive Ltda." },
  { nome: "Itatiaia Móveis S/A" },
  { nome: "Itesa Ltda." },
  { nome: "Itw Delfast Do Brasil Ltda." },
  { nome: "Jardim Sistemas Automotivos E Industriais S/A." },
  { nome: "Jjgc Ind. E Com. De Materiais " },
  { nome: "Jonhson Controls Br Aut. Ltda." },
  { nome: "Kalman Metalúrgica Kalindus Ltda." },
  { nome: "Karina Ind. E Com. Plásticos" },
  { nome: "Kassio Galvão De Castro - Kgx" },
  { nome: "Kato Estamparia Ind. E Com. Ltda." },
  { nome: "Keiper Do Brasil Ltda." },
  { nome: "Keiper Tecnologia De Assentos Automotivos Ltda." },
  { nome: "Kellogg Brasil & Cia." },
  { nome: "Key Serv Ind. E Com. Ltda." },
  { nome: "Kf Ind. E Comércio De Peças" },
  { nome: "Kidde Brasil Ltda." },
  { nome: "Kodak Alaris Manaus Ind E Com De Material Fotogr Ltda." },
  { nome: "Kodak Brasileira Comércio E Industria Ltda." },
  { nome: "Kodak Da Amazônia Industria E Comércio Ltda." },
  { nome: "Kondustec Ind. E Com. De Chicotes Elétricos Ltda." },
  { nome: "Kongsberg Automotive Ltda." },
  {
    nome: "Ktrmoes Ff Ind. De Auto Peças E Comp. Eletro Eletrônicos Ltda.-Erp",
  },
  { nome: "Kurashiki Chemical Products Do Brasil Ltda." },
  { nome: "Laboratorio Far Pe Gov Miguel Arraes S/A" },
  { nome: "Labortex Ind. E Com. Prod. De Borracha Ltda." },
  { nome: "Lang Mekra Do Brasil Ltda." },
  { nome: "Laticínio São João Ltda." },
  { nome: "Laticínios Douraleite Industria E Comercio Ltda." },
  { nome: "Laticínios Vale Do Pontal Ltda." },
  { nome: "Laticínios Vazleite Ind. E Com Ltda." },
  { nome: "Legget E Platt Do Brasil Ltda." },
  { nome: "Lg Philips Displays Brasil Ltda." },
  { nome: "Linpac Pisani Ltda." },
  { nome: "Litens Automotive Do Brasil Ltda." },
  { nome: "Litton Do Brasil Ltda." },
  { nome: "Lorenzetti S/A" },
  { nome: "Lorenzetti S/A Indústrias Brasileiras Eletrometalúrgicas" },
  { nome: "Ltm Ind E Com De Chicotes Eletr. Ltda." },
  { nome: "Lupatech S.A." },
  { nome: "Mackro Usinagem Ltda." },
  { nome: "Maggion Industrias De Pneus E Máquinas Ltda." },
  { nome: "Magius Metalúrgica Ind S/A" },
  { nome: "Magna Do Brasil Prod. Serv. Automotivos Ltda." },
  { nome: "Magneti Marelli Escapamentos Ltda." },
  { nome: "Magneti Marelli Sistemas Automotivos Ind. E Com. Ltda." },
  { nome: "Mahle Metal Leve S/A" },
  { nome: "Mahle Mmg Ltda." },
  { nome: "Makitron Ind. E Com. Ltda." },
  { nome: "Mangels Indústria E Comércio Ltda." },
  { nome: "Manoel Mory & Irmão Ltda." },
  { nome: "Marcegaglia Do Brasil Ltda." },
  { nome: "Marelli Cofap Do Brasil Ltda." },
  { nome: "Marppel Indústria E Comércio Ltda." },
  { nome: "Marro Maquinas Operatrizes Ltda." },
  { nome: "Massucato Ind. E Com. Ltda." },
  { nome: "Matripolo Moldes E Injetados Ltda." },
  { nome: "Maxbolt Indústria E Comércio De Metais S/A" },
  { nome: "Maxfor Ind. E Com. Ltda." },
  { nome: "Maxi Plating Eletrodeposição De Metais Ltda." },
  { nome: "Mb Metalbages Do Brasil Ltda." },
  { nome: "Mcs Industrial Ltda." },
  { nome: "Meadwestvaco Calmar Brasil Produtos Plásticos Ltda." },
  { nome: "Mecalfe/Recaje - Mec.Prec. Ltda." },
  { nome: "Mecaplast Do Brasil Ltda." },
  { nome: "Mega Plast S/A Ind. De Pl Sticos" },
  { nome: "Megastamp Industrial Ltda." },
  { nome: "Meincol Distribuidora De Aços S.A." },
  { nome: "Melhor Bocado Alimentos Ltda." },
  { nome: "Melida Comércio E Industria Ltda." },
  { nome: "Merck Sharp E Dohme Farm E Vet Ltda." },
  { nome: "Meridian Auto Systems" },
  { nome: "Meritor Do Brasil" },
  { nome: "Merk Sharp & Dohme Farm.Vet.Ltda." },
  { nome: "Metagal Indústria E Comércio Ltda." },
  { nome: "Metal 2 Ind. E Com. Ltda." },
  { nome: "Metal Linx Ltda." },
  { nome: "Metalgrafica Cearense S/A - Mecesa" },
  { nome: "Metalmix Usinagem Ind. Ltda." },
  { nome: "Metalplix Indústria Comércio Importação E Exportação Ltda." },
  { nome: "Metalrezende Ind. E Com. Imp. Exp. De Peças Veiculares Ltda." },
  { nome: "Metaltork Ind. Com. De Autopeças" },
  { nome: "Metalurgica Barra Do Pirai" },
  { nome: "Metalúrgica Cavelagni Indústria E Comércio Ltda. " },
  { nome: "Metalúrgica Denk Ltda." },
  { nome: "Metalúrgica Desa Ltda." },
  { nome: "Metalúrgica Ds Ltda." },
  { nome: "Metalúrgica Ecotech Ltda." },
  { nome: "Metalúrgica Galmar Ltda." },
  { nome: "Metalurgica Hame Ltda." },
  { nome: "Metalúrgica Jardim Ltda." },
  { nome: "Metalúrgica Knif Ltda." },
  { nome: "Metalúrgica Mardel Ltda." },
  { nome: "Metalúrgica Martins & Martins Ind E Com Ltda." },
  { nome: "Metalúrgica Nakayone Ltda." },
  { nome: "Metalúrgica Nunes Ltda." },
  { nome: "Metalúrgica Onix Ind. Com. Exp. E Imp Ltda." },
  { nome: "Metalúrgica Onnix Indústria E Comércio Ltda." },
  { nome: "Metalúrgica Quasar Ltda." },
  { nome: "Metalurgica Schadek Ltda." },
  { nome: "Metalúrgica Schadek Ltda." },
  { nome: "Metalúrgica Schwarz S/A." },
  { nome: "Metalúrgica Sete De Setembro Da Amazonia" },
  { nome: "Metalúrgica Sete De Setembro Ltda." },
  { nome: "Metalúrgica Suprens Ltda." },
  { nome: "Metalúrgica Utimec Ltda.-Parafusos E Peças" },
  { nome: "Metalúrgica Zen S/A" },
  { nome: "Metalway Industrial Ltda." },
  { nome: "Metalzul - Indústria Metalúrgica E Comercio Ltda." },
  { nome: "Metapar Usinagem Ltda." },
  { nome: "Methaf Autopartes Ltda." },
  { nome: "Mgfreios Ind. Com. De Auto Peças Ltda. - Epp" },
  { nome: "Mgl - Mecânica De Precisão" },
  { nome: "Microfio Ind. De Condutores Elétricos Ltda." },
  { nome: "Micromazza-Pmp Ltda." },
  { nome: "Midori Auto Leather Brasil Ltda." },
  { nome: "Mikropar Indústria E Comércio Ltda." },
  { nome: "Mineração Descalvado Ltda." },
  { nome: "Mm Sistemas Automotivos Ind. E Com Ltda." },
  { nome: "Modine Do Brasil Sistemas Termicos Ltda." },
  { nome: "Mondicap Ind. Com. E Serviços Ltda." },
  { nome: "Montepino Ltda." },
  { nome: "Mte Thomson Ind. Com. Ltda." },
  { nome: "Mubea Do Brasil Ltda." },
  { nome: "Multiforja S/A. Ind. E Com." },
  { nome: "Muriaço Estamparia De Metais Ltda." },
  { nome: "Murta Especialidades Químicas Ltda." },
  { nome: "Musashi Da Amazônia Ltda." },
  { nome: "Mvc Componentes Plasticos Ltda." },
  { nome: "Mz Usinafer Usinagem Ltda. Epp  " },
  { nome: "Nachi Brasil Ltda." },
  { nome: "Neo Steel S.A" },
  { nome: "Neobor Ind. E Com. Ltda." },
  { nome: "Neotec Industria E Com.De Pneus Ltda." },
  { nome: "Neve Indústria E Comércio De Prod. Cirúrgicos Ltda." },
  { nome: "Neve Premium Indústria E Comércio De Produtos Cirúrgicos Ltda." },
  { nome: "New Cast Ind. E Com. Ltda." },
  { nome: "New Horizon Coml. Ltda." },
  { nome: "New Hubner Componentes Automotivos" },
  { nome: "New Oldany Ind. Plástica E Metalúrgica Ltda." },
  { nome: "Niken Indústria E Comércio Metalúrgica Ltda." },
  { nome: "Nino Faróis Indl. E Exportadora Ltda." },
  { nome: "Niterra Do Brasil Ltda." },
  { nome: "Nitto Denko America Latina Ltda." },
  { nome: "Norgren Ltda." },
  { nome: "Nova Mix Industrial E Comercial De Alimentos Ltda." },
  { nome: "Nylok Tecnologia Em Fixação Ltda." },
  { nome: "O.G.C. Molas Industriais Ltda." },
  { nome: "Oerlikon Friction Systems Brasil Ltda." },
  { nome: "Omr Componentes Automotivos" },
  { nome: "Orion S.A" },
  { nome: "Orsa Celulose Pap E Bem Sa" },
  { nome: "Orsa Embalagens Da Amazônia S.A." },
  { nome: "Ouro Fino Ind. Com. Auto Peças Ltda." },
  { nome: "Oxiteno S/A Indústria E Comércio" },
  { nome: "Paranoá Industria De Borracha S.A." },
  { nome: "Parnaplast Ind. De Plásticos Ltda." },
  { nome: "Pastore Da Amazônia S.A." },
  { nome: "Paula && Amon Ltda. - Paulamon" },
  { nome: "Pce - Papel, Caixas E Embalagens S/A" },
  { nome: "Peguform Do Brasil Ltda." },
  { nome: "Pelzer Do Brasil Ltda." },
  { nome: "Perdigão Agroindustrial S.A" },
  { nome: "Perto S.A" },
  { nome: "Petroflex Ind. E Com. S/A" },
  { nome: "Petrowax Indústria E Comércio De Lubrificantes Ltda." },
  { nome: "Philips Do Brasil Ltda." },
  { nome: "Philips Do Brasil Ltda. - Div. Reatores" },
  { nome: "Philips Do Brasil Ltda. - Lighting" },
  { nome: "Philips Eletrônica Da Amazônia Ltda." },
  { nome: "Pichinin Industria E Comercio Ltda." },
  { nome: "Pinguim Indústria E Comércio De Radiadores Ltda. " },
  { nome: "Pintak Tratamento De Superfícies Ltda.   " },
  { nome: "Piramidal Termoplásticos Ltda." },
  { nome: "Pisani Plásticos S.A" },
  { nome: "Pk Cables Do Brasil Industria E Comércio Ltda." },
  { nome: "Plantec Polímeros Industrial Ltda." },
  { nome: "Plascar Ind Compon Plasticos Ltda." },
  { nome: "Plasfan Ind. E Com. De Plásticos Ltda." },
  { nome: "Plasmotec Plásticos Industriais Ltda." },
  { nome: "Plasolution Industria E Comercio De Plasticos Ltda." },
  { nome: "Plásticos Ibracil Ltda." },
  { nome: "Plásticos Maradei Ind. E Com. Ltda." },
  { nome: "Plasticos Mauá Ltda." },
  { nome: "Plásticos Mineiro Peças Técnicas Ltda." },
  { nome: "Plasticos Mueller" },
  { nome: "Plasvik Ind. De Prod. Plásticos Ltda." },
  { nome: "Plp - Produtos Para Linhas Preformados Ltda." },
  { nome: "Pma Indústria E Comércio Ltda. - Epp" },
  { nome: "Po Lighting Do Brasil Ltda." },
  { nome: "Pochet Do Brasil Indústria E Comércio Ltda." },
  { nome: "Polimetri Industria Metalúrgica Ltda." },
  { nome: "Ppe Fios Esmaltados S.A." },
  { nome: "Pressac Do Brasil Ltda." },
  { nome: "Prestec Prest. Serviços Em Qualidade" },
  { nome: "Prima Sole Componentes Automotivos Ltda." },
  { nome: "Primo Industrial Termoplásticos Ltda." },
  { nome: "Proaroma Industria E Comércio Ltda." },
  { nome: "Produflex Indústria De Borrachas Ltda." },
  { nome: "Produtos Alimentícios Superbom Ind Com Ltda." },
  { nome: "Progeral Ind. Artefatos Plasticos Ltda." },
  { nome: "Prolind Industrial Ltda." },
  { nome: "Prometal Beneficiamento E Consultoria Ltda." },
  { nome: "Pro-Serv Indústria Mecânica Ltda." },
  { nome: "Proturbo Usinagem De Precisão Ltda." },
  { nome: "Pst Ind. Eletrônica Da Amazônia" },
  { nome: "Qualystamp Estamparia E Ferramentaria Ltda." },
  { nome: "Quimvale" },
  { nome: "Quirios Produtos Químicos Ltda." },
  { nome: "Raco Do Brasil Ltda." },
  { nome: "Radiadores Marechal Ltda." },
  { nome: "Radiadores Visconde Ltda." },
  { nome: "Radio Frigor Ltda." },
  { nome: "Raposo Ind. E Comércio De Plásticos Ltda." },
  { nome: "Rassini Nhk Autopeças Ltda." },
  { nome: "Rcastro & Cia Ltda." },
  { nome: "Refal Ind. Com. De Rebites E Rebit. Ltda." },
  { nome: "Refal Rebites E Rebitadeiras Ltda." },
  { nome: "Reis Comércio E Indústria Metalúrgica Ltda." },
  { nome: "Remy Automotive Brasil Ltda." },
  { nome: "Requiph Ind. E Com. De Equipamentos Hidráulicos Ltda." },
  { nome: "Resil Ind. E Com. Ltda." },
  { nome: "Resiplastic Indústria E Comércio Ltda." },
  { nome: "Retengax Vedações Técnicas" },
  { nome: "Revestcar Ind. E Com.De Confecções Ltda." },
  { nome: "Rexnord Correntes Ltda." },
  { nome: "Rhodia Poliamida E Especialidades Ltda." },
  { nome: "Rhodiaco Industriais Químicas Ltda." },
  { nome: "Riclan S/A." },
  { nome: "Rigesa Da Amazonia S.A." },
  { nome: "Rima Industrial S/A" },
  { nome: "Rinnai Brasil Tecnologia De Aquecimento Ltda." },
  { nome: "Rio Capim Caulim S/A." },
  { nome: "Rivets Indústria E Comércio Ltda." },
  { nome: "Robrasa Rolamentos Espec Rothe Erde" },
  { nome: "Rtw - Rubber Technical Works" },
  { nome: "Rute Duran Martins" },
  { nome: "S-3 Industrial Ltda." },
  { nome: "Saargummi Bahia Ltda." },
  { nome: "Saargummi Do Brasil Ltda." },
  { nome: "Sachs Automotive Brasil Ltda." },
  { nome: "Sai - Automotive Do Brasil Ltda." },
  { nome: "Saint Gobain" },
  { nome: "Saint Gobain Abrasivos Ltda." },
  { nome: "Saint Gobain Quartzolit Ltda." },
  { nome: "Saint Gobain Sekurit Modular" },
  { nome: "Saint Gobain Vidros S.A" },
  { nome: "Saint-Gobain Brasil Prod.Ind. P/Construção Ltda." },
  {
    nome: "Saint-Gobain Do Brasil Produtos Industriais E Para Construção Ltda. (Gravataí-Rs)",
  },
  { nome: "Sakura Tech Brasil Ferramentaria E Moldagem Plástica Ltda." },
  { nome: "Samber Camp Industria Met. Plásticos S/A" },
  { nome: "Sampel Ind. De Peças Automotivas Ltda." },
  { nome: "Sanoh Do Brasil Ind. E Com. De Prod. Automotivos" },
  { nome: "Sanrisil S.A." },
  { nome: "Sansuy S.A. Indústria De Plásticos" },
  { nome: "São Marco Ind. E Com Ltda." },
  { nome: "Sat Belfort-Usinagem Indústria E Comércio Ltda." },
  { nome: "Sav-Tec Ind. De Comp. Metálicos Ltda. - Epp" },
  { nome: "Scania Latin America" },
  { nome: "Schenectady Brasil Ltda." },
  { nome: "Scheuermann + Helig Do Brasil Tec.E, Peças Estam. Dobradas" },
  { nome: "Schneider Electric Brasil Ltda." },
  { nome: "Schott Do Brasil" },
  { nome: "Schott Glaverbel Do Brasil Ltda." },
  { nome: "Schrader Bridgeport Do Brasil Ltda." },
  { nome: "Schrader International Brasil Ltda." },
  { nome: "Schulz Compressores Ltda." },
  { nome: "Scorpios Da Amazônia Ltda." },
  { nome: "Scorpios Indústria Metalúrgica Ltda." },
  { nome: "Seara Alimentos Ltda." },
  { nome: "Seeber Fastplas Ltda." },
  { nome: "Selco Vedações Dinâmicas Ltda." },
  { nome: "Selzer Automotiva Do Brasil Ltda." },
  { nome: "Semage Manutenção Industrial Ltda." },
  { nome: "Senior Do Brasil" },
  { nome: "Senior Flexonics Do Brasil Ltda." },
  { nome: "Seoyon Fabr. De Sistema Interior Automotivo Brasil Ltda." },
  { nome: "Serviço Nacional De Aprendizagem Industrial-Senai" },
  { nome: "Sicap Industria E Comércio Ltda." },
  { nome: "Siderurgica Barra Mansa Sa" },
  { nome: "Siemens Eletroeletrônica S.A" },
  { nome: "Siemens Vdo Automotive Ltda." },
  { nome: "Sika Automotive Ltda." },
  { nome: "Sika S/A" },
  { nome: "Sila Do Brasil Ltda." },
  { nome: "Silmafer Indústria Ltda." },
  { nome: "Sistemas De Implantes Nacionais E De Próteses Comércio Ltda." },
  { nome: "Sitmed Equipamentos Médicos Ltda." },
  { nome: "Skanparts Do Brasil Ltda." },
  {
    nome: "Smart Modular Technologies Indústria De Componentes Eletrônicos Ltda.",
  },
  { nome: "Sms Tecnologia Eletrônica Ltda." },
  { nome: "Sociedade Educacional São Paulo Apóstolo" },
  { nome: "Sodexo Do Brasil Comercial Ltda." },
  { nome: "Sofape S/A" },
  { nome: "Sogefi Filtration Do Brasil Ltda." },
  { nome: "Sol Nac - Indústria E Comércio De Plásticos Ltda." },
  { nome: "Soma Soluções Magnéticas Ind. E Com. Ltda." },
  { nome: "Soretto Fábrica De Cabos Automotivos S/A" },
  { nome: "Sortex Plásticos E Metais Ltda." },
  { nome: "Souza Cruz S.A." },
  { nome: "Spal Ind. Brasileira De Bebidas S/A" },
  { nome: "Spi Ind E Com De Prod Automotivos Lt" },
  { nome: "Splice Do Brasil - Telec. Eletric. S/A" },
  { nome: "Stampart Ind. E Com. Ltda." },
  { nome: "Stampart Peças Técnicas Flexíveis Ltda." },
  { nome: "Stamptec Ind. E Com De Peças Estampadas Ltda." },
  { nome: "Sumidenso Da Amazonia Ind. Eletricas Ltda." },
  { nome: "Sx Industrial De Plásticos Ltda." },
  { nome: "Syngenta Proteção De Cultivos Ltda." },
  { nome: "Synteko Produtos Químicos S/A" },
  { nome: "Tambau Industria Alimenticia Ltda." },
  { nome: "Tansan Industria Química - Sibelco" },
  { nome: "Tapon Corona Metal Plásticos Ltda." },
  { nome: "Tca - Tecn. Em Componentes Aut. S/A" },
  { nome: "Tec Bor Borracha Técnica Ltda." },
  { nome: "Tecalon Bras. De Auto Pecas S.A. " },
  { nome: "Technousi Almar Ind. E Com. De Auto Peças E Usinagem Ltda." },
  { nome: "Techseal Vedacoes Tecnicas Ltda." },
  { nome: "Tecmecanic Mec. De Precisão Ltda." },
  { nome: "Tecmecanic Mecânica De Precisão Ltda." },
  { nome: "Tecnaut Ind E Com De Metais Ltda." },
  { nome: "Tecnopeças Peças Técnicas E Fitas Adesivas Ltda." },
  { nome: "Tecnoperfil Taurus Ltda." },
  { nome: "Tecnoplast Industria E Comércio Ltda." },
  { nome: "Tecnowork Ind E Com De Plásticos Ltda." },
  { nome: "Tectubos Tecnologia Em Tubos Industria E Comércio Ltda." },
  { nome: "Telcon Fios E Cabos Para Telecomunicações S/A" },
  { nome: "Termomecânica São Paulo S.A" },
  { nome: "Tessin Ind. E Com. Ltda." },
  { nome: "Texfyt Industria E Comércio Ltda." },
  { nome: "Textil Assef Maluf Ltda." },
  { nome: "Thermix Tratamento Térmico Ltda." },
  { nome: "Thyssen Krupp Automotive Systems Do Brasil" },
  { nome: "Thyssen Krupp Metalúrgica Santa Luzia S/A" },
  { nome: "Ti Automotive Do Brasil" },
  { nome: "Timken Do Brasil" },
  { nome: "Timken Do Brasil Comércio E Indústria Ltda." },
  { nome: "Tkm Indústria De Borrachas E Plásticos Ltda." },
  { nome: "Tme Tecnologias Mec. E Eletronicas" },
  { nome: "Tomiyoshi Takaki - Pintak" },
  { nome: "Tormep - Tornearia Mecânica De Precisão Ltda." },
  { nome: "Tower Automotive" },
  { nome: "Toyota Boshoku Do Brasil Ltda." },
  { nome: "Toyota Do Brasil Ltda." },
  { nome: "Transtechnology Brasil Ind. E Com. Ltda." },
  { nome: "Treelleborg Automotive - Avs - Getoflex Ltda." },
  { nome: "Truck Bus - Indústria E Comércio De Auto Peças Ltda." },
  { nome: "Ttb Indústria E Comércio De Produtos Metálicos Ltda." },
  { nome: "Tupy Fundi€Âes Ltda." },
  { nome: "Ugimag Do Brasil Ind, Com. Prod. Mag. Ltda." },
  { nome: "Uliana Indústria Metalúrgica Ltda." },
  { nome: "Umicore Brasil" },
  { nome: "Unespa - União De Ensino Superior Do Pará" },
  {
    nome: "Uniforja - Cooperativa Central De Produção Industrial De Trabalhadores Em Metalurgia",
  },
  { nome: "Uniroyal Química S/A." },
  { nome: "Universal Indústria Metalúrgica Ltda." },
  { nome: "Universidade Castelo Branco - Ucb" },
  { nome: "Universidade De Caxias Do Sul" },
  { nome: "Universidade Do Estado Do Pará" },
  { nome: "Universidade Estadual Do Pará (Campus 2)" },
  { nome: "Universidade Estadual Paulista Julio De Mesquita Filho" },
  { nome: "Uralita Ind. E Com. Ltda." },
  { nome: "Urba Brosol" },
  { nome: "Urepol Polímeros Ltda." },
  { nome: "Usiparts S.A. - Sistemas Automotivos" },
  { nome: "Usival - Usinagem Valenciana Ltda." },
  { nome: "V.C.L. - Componentes De Vidro Ltda." },
  { nome: "Vale Verde Emp.Agrícolas Ltda. - Ubf (Mega)" },
  { nome: "Valeo Do Brasil" },
  { nome: "Valeo Sistemas Automotivos Ltda." },
  { nome: "Vallourec Do Brasil Ltda." },
  { nome: "Válvulas Schrader Do Brasil S.A" },
  { nome: "Vantico Ltda." },
  { nome: "Vema Eletro Eletrônica Ltda." },
  { nome: "Vertex Comércio E Industria Ltda." },
  { nome: "Veyance Technologies Do Brasil Produtos De Engenharia Ltda." },
  { nome: "Vibrasil Ind. De Artef. De Borracha Ltda." },
  { nome: "Vicunha Textil S/A" },
  { nome: "Videolar S.A." },
  { nome: "Viniartefatos Com. Importação Exportação" },
  { nome: "Vmg Indústria Metalúrgica" },
  { nome: "Voestalpine Meincol S.A" },
  { nome: "Volkswagem Do Brasil Ltda. " },
  { nome: "Voltru Fitas Ltda." },
  { nome: "Volvo Do Brasil Veículos Ltda. " },
  { nome: "Voss Automotive Ltda." },
  { nome: "Vulkan Do Brasil Ltda." },
  { nome: "Wabtec Brasil Fabricação E Manutenção De Equipamentos Ltda." },
  { nome: "Wahler Metalurgica Ltda." },
  { nome: "Wap Metal Ind. E Com De Molas E Estampados Ltda." },
  { nome: "Weener Industria Plastica Ltda." },
  { nome: "Weg Industrias S/A" },
  { nome: "Weidmann Tecnologia Em Plásticos Ltda." },
  { nome: "Whb Fundicao S/A" },
  { nome: "Wheaton Brasil Vidros Ltda." },
  { nome: "Wiest Tubos E Componentes Ltda." },
  { nome: "Wirex Cable S/A" },
  { nome: "Yadoya Industria E Comércio S/A" },
  { nome: "Yamaha Motor Da Amazônia" },
  { nome: "Yamaha Motor Do Brasil Ltda. " },
  { nome: "Yamaha Motors Do Brasil" },
  {
    nome: "Yapp Brasil Fabricacao De Tanques E Reservatorios Para Veiculos Automotores Ltda.",
  },
  { nome: "York S.A. Industria E Comércio" },
  { nome: "Ytk Motta Ind.Com.Tubos E Peças Ltda." },
  { nome: "Yunque Industrial Ltda." },
  { nome: "Zamprogna S/A" },
  { nome: "Zanandrear E Cia Ltda." },
  { nome: "Zanettini Barossi S/A Ind. E Comércio" },
  { nome: "Zanotti S/A" },
  { nome: "Zen S/A Industria Metalúrgica" },
  { nome: "Zincagem Martins Ltda." },
  { nome: "3M Do Brasil" },
];
