export default [
  {
    nome: "CEP - Controle Estatístico do Processo",
    id: 0,
    desc: [
      "Apresentar as técnicas de CEP para se analisar e controlar variação de características críticas de processos e de produtos de tal forma a atingir a sua estabilidade pelo conhecimento de causas especiais de variação e retroalimentação preventiva do processo, diminuindo-se assim paulatinamente a variação destas características e o aumento da capacidade de se atender aos requisitos do cliente.",
      "Compatível com os requisitos da IATF 16949:2016 e Manual CEP 2ª Edição - AIAG",
    ],
    tag: "Qualidade / Estatistica",
    time: "08h",
    programa: [
      "Conceito de variação",
      "Distribuição contínua e discreta",
      "Análise do processo pelo Histograma",
      "Causas comuns e causas especiais",
      "Gráfico de Controle e Diário-de-Bordo",
      "Cálculo dos parâmetros de centralização e dispersão do processo",
      "Conhecendo a distribuição Norma",
      "Elaboração, cálculos e análise completa de uma Carta de Médias",
      "Elaboração, cálculos e análise completa de uma Carta de Indivíduos",
      "Capabilidade Potencial do Processo",
      "Capabilidade de Desempenho do Processo",
      "Apresentação das Cartas de Atributos np, p, c e u",
      "Elaboração e análise das Cartas de Atributos",
      "Capabilidade do Processo para Atributos",
      "Análise de Normalidade para Atributos",
    ],
    publico:
      "Gerentes de processo, supervisores, engenheiros industriais, administradores de produção, metrologistas, gestores da qualidade, green belts, black belts.",
  },
  {
    nome: "CEP Avançado - Controle Estatístico do Processo Avançado",
    id: 1,
    desc: [
      "Apresentar esta ferramenta estatística, de requisito automotivo, para se analisar e controlar variação de características críticas de processos e de produtos de tal forma a atingir a sua estabilidade pelo conhecimento de causas especiais de variação e retroalimentação preventiva do processo, diminuindo-se assim a variação destas características e o aumento da Capabilidade do processo.",
      "Compatível com os requisitos da IATF 16949:2016 e Manual CEP 2ª Edição - AIAG",
    ],
    tag: "Qualidade / Estatistica",
    time: "16h",
    programa: [
      "Revisão dos conceitos de CEP",
      "Teste de Normalidade",
      "Conhecendo em profundidade a Distribuição Normal",
      "Tratativa para Processos Não-Normais",
      "Gráfico de Farol",
      "Carta de Zonas",
      "Carta para Pequenos Lotes",
      "CUSUM - Carta de Controle de Soma Acumulativa",
      "EWMA - Carta de Médias Móveis Exponencialmente Ponderadas",
      "Plano de Controle e Características Críticas",
      "Análise de Repetitividade e Reprodutibilidade da Medição",
      "Aplicações de exercícios com software.",
    ],
    publico:
      "Gerentes de processo, supervisores, engenheiros industriais, administradores de produção, gestores da qualidade, green belts, black belts.",
  },
  {
    nome: "MSA 4ª Edição - Análise do Sistema de Medição",
    desc: [
      "Capacitar os participantes a planejar, elaborar e analisar os diversos estudos dos Sistemas de Medição como Repetitividade, Reprodutibilidade, Calibração, Estabilidade, Desempenho, Tendência e Linearidade, Técnicas por Atríbutos, seguindo diretrizes do manual de MSA (AIAG - 4º Edição).",
    ],
    id: 2,
    tag: "Sistema de Medição",
    time: "16h",
    programa: [
      "Calibração do sistema de medição",
      "Revisão do MSA conforme instabilidade da Carta de Controle",
      "Preenchimento da planilha de MSA",
      "Fontes de Variação da Repetitividade",
      "Fontes de Variação da Reprodutibilidade",
      "Influência da amostragem na variação peça-a-peça",
      "Critérios para cálculo da %RR",
      "Análise gráfica do Sistema de Medição",
      "Conceito e Análise do n.d.c. aceitável",
      "Técnicas para tornar o n.d.c. aceitável",
      "Influência da %RR na capacidade potencial do processo",
      "Análise de Variância (ANOVA)",
      "Como proceder no caso de um sistema de medição não-replicável",
      "Estabilidade do sistema de medição (análise)",
      "Importância da distribuição das médias",
      "Entendendo as tabelas Z-Normal, t-Student e F-Snedecor",
      "Cálculos e critérios de aprovação da Tendência",
      "Curva de desempenho do sistema de medição",
      "Estudo de MSA por Atributos: eficiência, classificação errada, falso alarme e método Kappa",
      "Técnica dos Sinais para sistemas passa-não-passa por Atributos",
      "Demonstração do software WinMSA para Análise do Sistema de Medição.",
    ],
    publico:
      "Engenheiros de produto e processo, metrologistas, técnicos da qualidade, supervisores, auditores da ISO TS 16949, Green-Belts, Black Belts, laboratoristas e inspetores.",
  },
];
