export default [
  {
    nome: "CEP - Controle Estatístico do Processo",
    id: 0,
    desc: [
      "Apresentar as técnicas de CEP para se analisar e controlar variação de características críticas de processos e de produtos de tal forma a atingir a sua estabilidade pelo conhecimento de causas especiais de variação e retroalimentação preventiva do processo, diminuindo-se assim paulatinamente a variação destas características e o aumento da capacidade de se atender aos requisitos do cliente.",
      "Compatível com os requisitos da IATF 16949:2016 e Manual CEP 2ª Edição - AIAG",
    ],
    tag: "Qualidade / Estatistica",
    tempo: "08h",
    programa: [
      "Conceito de variação",
      "Distribuição contínua e discreta",
      "Análise do processo pelo Histograma",
      "Causas comuns e causas especiais",
      "Gráfico de Controle e Diário-de-Bordo",
      "Cálculo dos parâmetros de centralização e dispersão do processo",
      "Conhecendo a distribuição Norma",
      "Elaboração, cálculos e análise completa de uma Carta de Médias",
      "Elaboração, cálculos e análise completa de uma Carta de Indivíduos",
      "Capabilidade Potencial do Processo",
      "Capabilidade de Desempenho do Processo",
      "Apresentação das Cartas de Atributos np, p, c e u",
      "Elaboração e análise das Cartas de Atributos",
      "Capabilidade do Processo para Atributos",
      "Análise de Normalidade para Atributos",
    ],
    publico:
      "Gerentes de processo, supervisores, engenheiros industriais, administradores de produção, metrologistas, gestores da qualidade, green belts, black belts.",
  },
  {
    nome: "CEP Avançado - Controle Estatístico do Processo Avançado",
    id: 1,
    desc: [
      "Apresentar esta ferramenta estatística, de requisito automotivo, para se analisar e controlar variação de características críticas de processos e de produtos de tal forma a atingir a sua estabilidade pelo conhecimento de causas especiais de variação e retroalimentação preventiva do processo, diminuindo-se assim a variação destas características e o aumento da Capabilidade do processo.",
      "Compatível com os requisitos da IATF 16949:2016 e Manual CEP 2ª Edição - AIAG",
    ],
    tag: "Qualidade / Estatistica",
    tempo: "16h",
    programa: [
      "Revisão dos conceitos de CEP",
      "Teste de Normalidade",
      "Conhecendo em profundidade a Distribuição Normal",
      "Tratativa para Processos Não-Normais",
      "Gráfico de Farol",
      "Carta de Zonas",
      "Carta para Pequenos Lotes",
      "CUSUM - Carta de Controle de Soma Acumulativa",
      "EWMA - Carta de Médias Móveis Exponencialmente Ponderadas",
      "Plano de Controle e Características Críticas",
      "Análise de Repetitividade e Reprodutibilidade da Medição",
      "Aplicações de exercícios com software.",
    ],
    publico:
      "Gerentes de processo, supervisores, engenheiros industriais, administradores de produção, gestores da qualidade, green belts, black belts.",
  },
  {
    nome: "CEP para Pequenos Lotes/Processos Contínuos",
    id: 1,
    desc: [
      "Apresentar as ferramentas estatísticas para controle e melhoria de Processos Contínuos, Bateladas ou Processos para Manufatura de Pequenos Lotes.",
    ],
    tag: "Qualidade / Estatistica",
    tempo: "08h",
    programa: [
      "Revisão do CEP (Normalização, Estabilização, Capabilidade);",
      "Conceituação de Pequenos Lotes;",
      "Padronização para Atributos;",
      "Gabaritos Estreitos;",
      "Como aplicar CEP na fabricação de Pequenos Lotes;",
      "Técnica Alvo / Nominal;",
      "Carta (X, R) para amostras de tamanho variável;",
      "Técnica Z;",
      "Cartas (X, S2) para Pequenos Lotes;",
      "Capacidade do Processo para Pequenos Lotes;",
      "Utilização do CEP em Processos Contínuos e Bateladas;",
      "Cálculo de Desvio Padrão para pequena amostragem;",
      "Cálculo dos Limites de Controle para Atributos que não possuam Distribuição Normal;",
      "Carta de Controle para Distribuição Não Normal;",
      "Cp e Cpk para Distribuição Não Normal;",
      "Apresentação do WinCEP para Pequenos Lotes;",
      "Exemplos reais de implantação de cartas para Pequenos Lotes, Processos Contínuos e Bateladas.",
    ],
    publico:
      "Gerentes de processo, supervisores, engenheiros industriais, administradores de produção, gestores da qualidade, green belts, black belts.",
  },
  {
    nome: "CEP Controle Estatístico do Processo Operacional (Para Operadores/Supervisores)",
    id: 1,
    desc: [
      "Apresentar as ferramentas básicas para: Identificação e Análise de Problemas, Avaliação da Estabilidade do Processo, Melhoria Contínua do Processo.",
    ],
    tag: "Qualidade / Estatistica",
    tempo: "08h",
    programa: [
      "Concientização para a Qualidade",
      "Fluxograma",
      "Histograma",
      "Causas Especiais x Causas Comuns de Variação",
      "Conceitos de Média e Amplitude",
      "Arredondamento de dados",
      "Interpretação da escala na carta de controle",
      "Elaboração dos Gráficos de Controle",
      "Interpretação Gráfica de tendências e causas especiais",
      "Diário de Bordo",
      "Preenchimento de Cartas de Controle",
      "Gráfico de Pareto e Diagrama Causa / Efeito",
      "Exemplos de aplicação",
    ],
    publico: "Operadores, Encarregados, Mestres, Líderes.",
  },
  {
    nome: "DOE - Projeto de Experimentos",
    id: 1,
    desc: [
      "Estabelecer uma Estratégia eficiente de ensaios / experimentação na área de Projeto do Produto / Processo, projetar produtos que atendam ou superem as expectativas dos clientes a um custo mínimo.",
    ],
    tag: "Qualidade / Estatistica",
    tempo: "16h",
    programa: [
      "PROJETO ROBUSTO",
      "FATORES CONTROLÁVEIS / PARÂMETROS DE PROJETO",
      "Relação Sinal / Ruído",
      "Técnicas para alcançar um ''PROJETO ROBUSTO''",
      "O que deve ser mudado na sistemática tradicional de Projeto",
      "Qualidade ''OFFLINE'' x Qualidade ''ONLINE''",
      "Como quebrar um Sistema em Subsistemas",
      "Como determinar a Função Ideal de um Sistema",
      "Função de Perda de Taguchi",
      "Planejamento de Experimentos para fatores a 2 níveis",
      "Planejamento de Experimentos para fatores a 3 níveis",
      "EVOP - Operação Evolucionária de Processos",
      "Trabalho em Equipes Constando de Desenvolvimento de um Projeto Robusto Utilizando Metodologia TAGUCHI",
      "Durante o Workshop será desenvolvida a Metodologia TAGUCHI para projeto de Parâmetros que consiste de sete etapas básicas",
      "1a Etapa - Seleção dos Fatores de Controle (Parâmetros)",
      "2a Etapa - Seleção dos Fatores de Ruído",
      "3a Etapa - Escolha da Matriz Ortogonal apropriada",
      "4a Etapa - Simulação Analítica (Experimentação)",
      "5a Etapa - Cálculo da relação Sinal / Áudio",
      "6a Etapa - Cálculo da tabela de Análise de Variância (ANOVA)",
      "7a Etapa - Análise dos Resultados e Conclusões.",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Projeto / Processo, Técnicos ligados à Qualidade e Produtividade, Técnicos ligados à Manufatura.",
  },
  {
    nome: "MSA 4ª Edição - Análise do Sistema de Medição",
    desc: [
      "Capacitar os participantes a planejar, elaborar e analisar os diversos estudos dos Sistemas de Medição como Repetitividade, Reprodutibilidade, Calibração, Estabilidade, Desempenho, Tendência e Linearidade, Técnicas por Atríbutos, seguindo diretrizes do manual de MSA (AIAG - 4º Edição).",
    ],
    id: 2,
    tag: "Sistema de Medição",
    tempo: "16h",
    programa: [
      "Calibração do sistema de medição",
      "Revisão do MSA conforme instabilidade da Carta de Controle",
      "Preenchimento da planilha de MSA",
      "Fontes de Variação da Repetitividade",
      "Fontes de Variação da Reprodutibilidade",
      "Influência da amostragem na variação peça-a-peça",
      "Critérios para cálculo da %RR",
      "Análise gráfica do Sistema de Medição",
      "Conceito e Análise do n.d.c. aceitável",
      "Técnicas para tornar o n.d.c. aceitável",
      "Influência da %RR na capacidade potencial do processo",
      "Análise de Variância (ANOVA)",
      "Como proceder no caso de um sistema de medição não-replicável",
      "Estabilidade do sistema de medição (análise)",
      "Importância da distribuição das médias",
      "Entendendo as tabelas Z-Normal, t-Student e F-Snedecor",
      "Cálculos e critérios de aprovação da Tendência",
      "Curva de desempenho do sistema de medição",
      "Estudo de MSA por Atributos: eficiência, classificação errada, falso alarme e método Kappa",
      "Técnica dos Sinais para sistemas passa-não-passa por Atributos",
      "Demonstração do software WinMSA para Análise do Sistema de Medição.",
    ],
    publico:
      "Engenheiros de produto e processo, metrologistas, técnicos da qualidade, supervisores, auditores da ISO TS 16949, Green-Belts, Black Belts, laboratoristas e inspetores.",
  },
  {
    nome: "Incerteza de Medição (Conforme ISO GUM)",
    desc: [
      "Capacitar os participantes na avaliação e expressão da incerteza de medição de grandezas físicas associadas a experimentos de pesquisa básica e aplicada, à métodos de calibração de instrumentos e padrões aumentando assim a eficácia no atendimento aos requisitos, às leis e regulamentos e às atividades contratuais.",
    ],
    id: 2,
    tag: "Sistema de Medição",
    tempo: "16h",
    programa: [
      "Conceitos Estatísticos",
      "Conceitos Probabilísticos",
      "Função Densidade de Probabilidade",
      "Distribuição Gaussiana",
      "Incerteza de Medição",
      "Fontes de Erros",
      "Erro Aleatório e Erro Sistemático",
      "Avaliação da Incerteza pela Análise Estatística",
      "Alternativa ao Método Estatístico",
      "Incerteza Padrão Combinada",
      "Incerteza Tipo A e Tipo B",
      "Incerteza Expandida",
      "Fator de Abrangência",
      "Lei da Propagação da Incerteza",
      "Metodologia de cálculo",
      "Registro de incerteza de medição",
      "Exemplos e exercícios de aplicação",
    ],
    publico:
      "Técnicos e outros profissionais associados à Medição, Instrumentação, Laboratórios, Pesquisa Aplicada e Garantia da Qualidade. ",
  },
  {
    nome: "APQP (2ª Edição): Planejamento Avançado da Qualidade do Produto",
    desc: [
      "Preparar os participantes para projetar ou atualizar o Sistema da Qualidade da Empresa, de modo a satisfazer os requisistos da IATF 16949.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "16h",
    programa: [
      "Organizar a equipe e definir o escopo",
      "Treinamento",
      "Engenharia simultânea",
      "Resolução de Problemas",
      "Voz do Cliente",
      "Plano de negócios e estratégia de marketing",
      "Estudos de confiabilidade do produto",
      "Objetivos da qualidade e da confiabilidade",
      "Lista de materiais, fluxograma e características de processo preliminar",
      "Plano de garantia do produto",
      "Noções de FMEA de projeto (DFMEA) e de projeto para montagem (DFA)",
      "Verificação e revisão do projeto",
      "Especificações de material e de engenharia",
      "Desenhos e eventuais mudanças",
      "Novos dispositivos, ferramentais, equipamentos e gabaritos (requisitos)",
      "Características especiais de produto e de processo",
      "Suporte da gerência para viabilidade da equipe",
      "Especificações de embalagem",
      "Revisão do sistema da qualidade",
      "Fluxograma e lay out do processo",
      "Matriz de características",
      "Noções de FMEA de processo (PFMEA)",
      "Análise do sistema de medição e de capacidade",
      "Corridas de produção",
      "Aprovação de peça de produção (noções de PPAP)",
      "Avaliação da embalagem",
      "Plano de controle (descrição de cada coluna)",
      "Redução da variação",
      "Entrega, serviço e Satisfação do Cliente melhorados",
      "Lições aprendidas e boas práticas",
      "Técnicas analíticas (QFD, Benchmarking, DOE, Poka-Yoke, etc.).",
    ],
    publico:
      "Diretores, Gerentes, Engenheiros do Projeto do Produto / Processo, Administradores da Produção, Técnicos ligados a Qualidade e Produtividade.",
  },
  {
    nome: "PPAP (4ª Edição): Processo de Aprovação de Peça de Produção",
    desc: [
      "Preparar os participantes para projetar ou atualizar o Sistema da Qualidade da Empresa, de modo a satisfazer os requisistos da TS16949.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "08h",
    programa: [
      "Propósitos do PPAP",
      "Requisitos de Projeto",
      "Relatórios de Composição de Material",
      "Alterações de Engenharia",
      "Diagrama de Fluxo",
      "FMEA e estudos de MSA",
      "Ensaios de materiais e de performance",
      "Estudos iniciais do processo",
      "Documentação de Laboratório Qualificado",
      "Amostra padrão e auxílios visuais",
      "Requisitos específicos do cliente",
      "Certificado de submissão (PSW) - níveis de submissão",
      "Notificação ao cliente",
      "Situações do PPAP",
      "Formulários utilizados no PPAP",
      "Retenção dos Registros",
    ],
    publico:
      "Diretores, Gerentes, Engenheiros do Projeto do Produto / Processo, Administradores da Produção, Técnicos ligados a Qualidade e Produtividade.",
  },
  {
    nome: "IMDS : International Material Data System (Integração com APQP e PPAP)",
    desc: [
      "Preparar os colaboradores para a realização do cadastramento e a elaboração do Sistema Internacional de Dados de Materiais.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "08h",
    programa: [
      "<h3>Generalidades:</h3>",
      "<span>O que é IMDS;</span>",
      "<span>Quando e onde surgiu o IMDS;</span>",
      "<span>Onde estão os requisitos de Clientes;</span>",
      "<span>Quando submeter;</span>",
      "<span>Porque submeter;</span>",
      "Cadeia de Fornecimento",
      "Cadastramento da Empresa",
      "<h3>Estrutura:</h3>",
      "<h3><span>Conceito:</span></h3>",
      "<span>Substâncias Básicas;</span>",
      "<span>Material;</span>",
      "<span>Semi-componentes;</span>",
      "<span>Componentes;</span>",
      "<h3><span>Tipos de Estruturas:</span></h3>",
      "<span>Estruturas Corretas;</span>",
      "<span>Estruturas Erradas;</span>",
      "Vantagens",
      "Desvantagens",
      "Sugestões",
      "Cadastramento de Produtos",
      "<h3>Criar um Datasheet:</h3>",
      "<span>Efetuando o Login;</span>",
      "<span>Criando a Estrutura;</span>",
      "<span>Informações adicionais;</span>",
      "<span>Enviando o Datasheet;</span>",
      "<span>Efetuando mudanças / reenviando Datasheet;</span>",
      "<span>Critério adicional de busca;</span>",
      "Como usar a função Copy",
      "Exemplos",
      "Número D-U-N-S",
      "Banco de Dados",
      "Exercícios.",
    ],
    publico:
      "Gerentes, Engenheiros do Projeto do Produto / Processo, Administradores da Produção, Técnicos ligados a Qualidade e Produtividade.",
  },
  {
    nome: "IATF 16949:2016 - Requisitos do Sistema de Gestão da Qualidade Automotiva",
    desc: [
      "Habilitar os participantes na Análise, Interpretação e Implementação dos requisitos da nova Norma IATF 16949:2016.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "16h",
    programa: [
      "Introdução à IATF 16949:2016",
      "Termos e definições da IATF 16949:2016",
      "A IATF 16949:2016 como complemento da ISO 9001:2015",
      "Abordagem de processo automotivo",
      "Contexto da Organização e as Partes Interessadas",
      "Pensamento Baseado em Risco",
      "Manuais de referência da AIAG: FMEA, CEP, MSA, APQP, PPAP",
      "Overview de Ferramentas da Qualidade, como DFA/DFM, TPM, POKA YOKE, GD&T, 8D, FTA e QFD",
      "Utilização adequada dos principais Core Tools",
      "Regras de certificação na Norma IATF 16949:2016.",
    ],
    publico:
      "Auditores Internos do SGQ / Organizações e profissionais que buscam a implementação e certificação IATF 16949:2016. / Organizações e profissionais interessados no processo de transição da ISO TS 16949:2009 para IATF 16949:2016.",
  },
  {
    nome: "IATF 16949:2016 - Requisitos e Formação de Auditor Interno - FAI",
    desc: [
      "Habilitar os participantes na Análise, Interpretação e Implementação dos requisitos da nova Norma IATF 16949:2016.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "24h",
    programa: [
      "<h3>1ª Parte - Análise, interpretação e implementação dos requisitos</h3>",
      "<span>Introdução à IATF 16949:2016</span>",
      "<span>Termos e definições da IATF 16949:2016</span>",
      "<span>A IATF 16949:2016 como complemento da ISO 9001:2015</span>",
      "<span>Análise e Interpretação dos requisitos da IATF 16949:2016</span>",
      "<span>Contexto da Organização e as Partes Interessadas</span>",
      "<span>Pensamento Baseado em Risco</span>",
      "<span>Manuais de referência da AIAG: FMEA, CEP, MSA, APQP, PPAP</span>",
      "<span>Overview de Ferramentas da Qualidade, como DFA/DFM, TPM, POKA YOKE, GD&T, 8D, FTA e QFD</span>",
      "<span>Utilização adequada dos principais <b>Core Tools</b></span>",
      "<h3>2ª Parte - Conceitos de Auditoria Interna</h3>",
      "<span>ABNT NBR <b>ISO 19011:2018</b>, Diretrizes para Auditoria de Sistema de Gestão</span>",
      "<span>Princípios de Auditoria</span>",
      "<span>Abordagem de risco</span>",
      "<span>Escopo e abrangência de Auditoria</span>",
      "<span>Objetivos do programa de Auditoria</span>",
      "<span>Método e critérios de Auditoria</span>",
      "<span>Responsabilidade da Direção e Gestor do processo de Auditoria</span>",
      "<span>Contexto da organização</span>",
      "<span>Sistema PDCA para Gestão de Auditoria</span>",
      "<span>Planejamento e implantação de um programa de Auditoria</span>",
      "<span>Monitoramento, análise crítica e melhoria de programa de Auditoria</span>",
      "<span>Como realizar uma Auditoria</span>",
      "<span>Evidências objetivas e constatações de Auditoria</span>",
      "<span>Preparação de relatório de Auditoria</span>",
      "<span>Reuniões de abertura e fechamento de Auditoria</span>",
      "<span>Registro de Não Conformidade e sua fundamentação</span>",
      "<span>Sugestões de oportunidades de melhoria</span>",
      "<span>Anexo A: novas diretrizes de Auditoria</span>",
      "<h3>3ª Parte: PRÁTICA DE AUDITORIA INTERNA</h3>",
      "<span>Elaboração de Check-list</span>",
      "<span>Elaboração do Relatório e Plano de Ação</span>",
      "<span>Elaboração do Plano de Ação Corretiva</span>",
      "<span>Análise do Plano de Gestão de Riscos</span>",
    ],
    publico:
      "Auditores Internos do SGQ / Organizações e profissionais que buscam a implementação e certificação IATF 16949:2016. / Organizações e profissionais interessados no processo de transição da ISO TS 16949:2009 para IATF 16949:2016.",
  },
  {
    nome: "VDA 6.3 - 3ª Edição - 2016 - Interpretação e Requisitos de Processo",
    desc: [
      "Assegurar aos fornecedores da indústria automotiva a correta interpretação dos requisitos da guia de Auditoria de Processo VDA 6.3 - 3ª Edição (versão 2016).",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "16h",
    programa: [
      "Estrutura da coleção de normas VDA",
      "Instruções e aplicações",
      "Tipos de Auditorias",
      "Qualificação de Auditores e Código de Conduta",
      "Identificação de Riscos, e avaliação de riscos",
      "Diagrama Tartaruga",
      "Visão global da norma VDA 6.3 na cadeia de abastecimento",
      "Avaliação Potencial-P1",
      "Avaliação das questões individuais, regras de rebaixamento e classificação",
      "Interpretação de requisitos e utilização do questionário da versão 2016",
    ],
    publico:
      "Diretores, gerentes, engenheiros de processo, gestores da qualidade, profissionais dos departamentos de compras e de desenvolvimento de fornecedores, auditores internos e técnicos ligados à garantia da qualidade.",
  },
  {
    nome: "VDA 6.3 - 3ª Edição - 2016- Requisitos e Formação de Auditor Interno de Processo - FAI",
    desc: [
      "Preparar fornecedores da indústria automotiva para auditarem e serem auditadas em seus processos produtivos conforme a norma VDA 6.3 (versão 2016).",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "24h",
    programa: [
      "<h3>1ª Parte: Auditoria de Processos</h3>",
      "<h3><span>I – Processo de Auditoria</span></h3>",
      "<span>Diagrama da Tartaruga</span>;",
      "<span>Análise de Risco;</span>",
      "<h3><span>II- Auditorias</span></h3>",
      "<span>Avaliação Potencial (P1);</span>",
      "<span>Avaliação Produto e Processo;</span>",
      "<h3><span>III - Requisitos da 6.3</span></h3>",
      "<span>Análise Potencial</span>;",
      "<span>Gerenciamento de Projeto;</span>",
      "<span>Planejamento de Desenvolvimento de Produto e Processo (P2, P3 e P4);</span>",
      "<span>Execução do Desenvolvimento de Produto e Processo;</span>",
      "<span>Gerenciamento de Fornecedores;</span>",
      "<span>Análise de Processo/Produção (P5, P6 e P7);</span>",
      "<span>Atendimento ao Cliente, Satisfação do Cliente e Serviços;</span>",
      "<h3><span>IV – Requisitos de Auditores</span></h3>",
      "<h3><span>V – Avaliação:</span></h3>",
      "<span>Geral;</span>",
      "<span>Transporte e Manuseio;</span>",
      "<h3>2ª Parte: PRÁTICA DE AUDITORIA INTERNA</h3>",
      "<h3><span>I –Workshop de Aplicação.</span></h3>",
      "<h3><span>Elaboração:</span></h3>",
      "<span>Check-list de Auditoria;</span>",
      "<span>Relatórios Análise de Riscos/Tartaruga;</span>",
      "<span>Relatório Aspectos Tecnológico;</span>",
      "<span>Plano de Ação Corretiva;</span>",
    ],
    publico:
      "Diretores, gerentes, engenheiros de processo, gestores da qualidade, profissionais dos departamentos de compras e de desenvolvimento de fornecedores, auditores internos e técnicos ligados à garantia da qualidade.",
  },
  {
    nome: "ISO 9001:2015 - Requisitos, Análise e Interpretação",
    desc: [
      "Compreender a estrutura dos sistemas de gestão baseados no Anexo SL",
      "Entender a Gestão de Riscos e sua relação com a ISO 9001:2015",
      "Integração da Gestão de Riscos com o Sistema de Gestão da Qualidade",
      "Implantação dos requisitos da ISO 9001:2015",
      "Apresentar aos participantes a nova estrutura da Norma ISO 9001:2015.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "08h",
    programa: [
      "Princípios de gestão da qualidade",
      "Sistema da Qualidade com base na Norma ISO 9001:2015, vocabulário, termos e definições",
      "Informação documentada",
      "Pensamento baseado em risco",
      "Abordagem por processos",
      "Ciclo PDCA",
      "Objetivos e Política da Qualidade",
      "Relacionamento com outras normas do sistema de gestão – Anexo SL",
      "Estratégias para adequação dos sistemas de gestão existentes aos requisitos ISO 9001:2015",
      "Ligação mais forte do SGQ - Sistema de Gestão da Qualidade com as estratégias e objetivos organizacionais",
      "<h3>ANÁLISE DOS REQUISITOS DA ISO 9001:2015:</h3>",
      "<span>Contexto da Organização;</span>",
      "<span>Liderança;</span>",
      "<span>Planejamento;</span>",
      "<span>Apoio;</span>",
      "<span>Operação;</span>",
      "<span>V – Avaliação:</span>",
      "<span>Avaliação de desempenho;</span>",
      "<span>Melhoria;</span>",
      "*<b>Todo o Treinamento será ilustrado com exemplos práticos de implementação da norma ISO 9001:2015 em organizações.</b>*",
    ],
    publico:
      "Diretores, gerentes, gestores da qualidade, auditores internos, consultores e profissionais vinculados ao Sistema de Gestão da Qualidade.",
  },
  {
    nome: "ISO 9001:2015 - Requisitos e Formação de Auditor Interno - FAI",
    desc: [
      "Compreender a estrutura dos sistemas de gestão baseados no Anexo SL",
      "Entender a Gestão de Riscos e sua relação com a ISO 9001:2015",
      "Integração da Gestão de Riscos com o Sistema de Gestão da Qualidade",
      "Implantação dos requisitos da ISO 9001:2015",
      "Fornecer diretrizes para instituir, planejar, executar e documentar as Auditorias de Sistemas de Gestão da Qualidade, com base na ISO 9001:2015.",
    ],
    id: 2,
    tag: "Gestão da Qualidade/Ambiental/Segurança e Saúde Ocupacional/Integrada",
    tempo: "16h",
    programa: [
      "Visão geral da ISO 9001:2015",
      "Sistema da Qualidade com base na Norma ISO 9001:2015, vocabulário, termos e definições",
      "Princípios de gestão da qualidade",
      "Informação documentada",
      "Pensamento baseado em risco",
      "Abordagem por processos",
      "Ciclo PDCA",
      "Objetivos e Política da Qualidade",
      "Relacionamento com outras normas do sistema de gestão – Anexo SL",
      "Estratégias para adequação dos sistemas de gestão existentes aos requisitos ISO 9001:2015",
      "Ligação mais forte do SGQ - Sistema de Gestão da Qualidade com as estratégias e objetivos organizacionais",
      "<h3>ANÁLISE DOS REQUISITOS DA ISO 9001:2015:</h3>",
      "<span>Contexto da Organização;</span>",
      "<span>Liderança;</span>",
      "<span>Planejamento;</span>",
      "<span>Apoio;</span>",
      "<span>Operação;</span>",
      "<span>Avaliação de desempenho;</span>",
      "<span>Melhoria;</span>",
      "<h3>CONCEITOS DA AUDITORIA INTERNA</h3>",
      "<span>ABNT NBR <b>ISO 19011:2018</b>, Diretrizes para Auditoria de Sistema de Gestão;</span>",
      "<span>Princípios de Auditoria;</span>",
      "<span>Abordagem de risco;</span>",
      "<span>Escopo e abrangência de Auditoria;</span>",
      "<span>Objetivos do programa de Auditoria;</span>",
      "<span>Método e critérios de Auditoria;</span>",
      "<span>Responsabilidade da Direção e Gestor do processo de Auditoria;</span>",
      "<span>Contexto da organização;</span>",
      "<span>Sistema PDCA para Gestão de Auditoria;</span>",
      "<span>Planejamento e implantação de um programa de Auditoria;</span>",
      "<span>Monitoramento, análise crítica e melhoria de programa de Auditoria;</span>",
      "<span>Como realizar uma Auditoria;</span>",
      "<span>Evidências objetivas e constatações de Auditoria;</span>",
      "<span>Preparação de relatório de Auditoria;</span>",
      "<span>Reuniões de abertura e fechamento de Auditoria;</span>",
      "<span>Registro de Não Conformidade e sua fundamentação;</span>",
      "<span>Sugestões de oportunidades de melhoria;</span>",
      "<span>Anexo A: novas diretrizes de Auditoria;</span>",
      "<h3>PRÁTICA DE AUDITORIA INTERNA</h3>",
      "<span>Elaboração do Check-List;</span>",
      "<span>Elaboração do Relatório e Plano de Ação;</span>",
      "<span>Elaboração do Plano de Ação Corretiva;</span>",
      "<span>Análise do Plano de Gestão de Riscos;</span>",
    ],
    publico:
      "Diretores, gerentes, gestores da qualidade, auditores internos, consultores e profissionais vinculados ao Sistema de Gestão da Qualidade.",
  },
  {
    nome: "FMEA AIAG-VDA 1ª Edição:2019 - Análise do Modo e Efeitos de Falha - Projeto e Processo",
    desc: [
      "A VTB tem assessorado montadoras como Ford, GM, Peugeot, VW e Fiat, assim como seus sistemistas, na elaboração e orientação de FMEA's de Projeto e de Processo. Nos últimos 15 anos a VTB desenvolveu com seus clientes mais de 1.200 FMEA's e revisou outros 550.Treinamos cerca de 1.800 colaboradores em montadoras e mais de 2.000 nas mais diversas áreas como as do setores médicos, eletrônico, de embalagem, farmacêutico, de alimentos e bebidas, madereiro, metalúrgico, da chamada linha branca, de geração de energia, dentre outros.",
      "Apresentar conceitos e estrutura de FMEA de Projeto, Processo e FMEA MSR, assim como capacitar os colaboradores no entendimento e aplicação eficaz de sua nova interpretação.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "16h",
    programa: [
      "Conceitos e Objetivos do FMEA",
      "Evolução histórica do FMEA",
      "Definição de DFMEA, PFMEA e FMEA MSR",
      "O que mudou do FMEA da AIAG 4ª edição para AIAG-VDA 1ª edição",
      "As 07 Etapas de Elaboração de um FMEA",
      "Construção das Estruturas de um FMEA",
      "Elemento em Foco e Estrutura Posterior e Inferior",
      "Funções de cada Estrutura do FMEA",
      "Características do Produto e do Processo",
      "Elemento 4M",
      "Conceito de Modo de Falha, Efeito e suas Causas Potenciais",
      "Análise das Tabelas de Severidade, Ocorrência e Detecção",
      "Conceito de Prioridade de Ação associada ao cálculo do Risco",
      "Tabela PA (Prioridade de Ação) e sua interpretação",
      "Ações derivadas da análise da Tabela PA (Otimização)",
      "Diagrama “P” para DFMEA e PFMEA",
      "Diagrama de Blocos, Fluxograma e Plano de Controle",
      "Trabalho em Equipe – Elaboração de FMEA de um produto da Empresa",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Projeto do Produto/Processo, Engenheiros / Técnicos de Manufatura, Técnicos ligados à Qualidade/Produtividade, Coordenadores de FMEA, Profissionais de Pesquisa e Desenvolvimento de Produto, Green Belts e Black Belts.",
  },
  {
    nome: "DFMEA AIAG-VDA - Análise do Modo e Efeito da Falha de Projeto - AIAG-VDA - 1ª Edição",
    desc: [
      "Apresentar conceitos e estrutura deste do DFMEA, assim como capacitar os colaboradores no entendimento e aplicação eficaz de sua nova interpretação.",
      "A VTB tem assessorado montadoras como Ford, GM, Peugeot, VW e Fiat, assim como seus sistemistas, na elaboração e orientação de FMEA's de Projeto e de Processo. Nos últimos 15 anos a VTB desenvolveu com seus clientes mais de 1.200 FMEA's e revisou outros 550.",
      "Treinamos cerca de 1.800 colaboradores em montadoras e mais de 2.000 nas mais diversas áreas como as do setores médicos, eletrônico, de embalagem, farmacêutico, de alimentos e bebidas, madereiro, metalúrgico, da chamada “linha branca”, de geração de energia, dentre outros.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "08h",
    programa: [
      "Conceitos e Objetivos do FMEA",
      "Evolução histórica do FMEA",
      "Definição de DFMEA e FMEA MSR",
      "O que mudou do FMEA da AIAG 4ª edição para AIAG-VDA 1ª edição",
      "As 07 Etapas de Elaboração de um DFMEA",
      "Construção das Estruturas de um DFMEA",
      "Elemento em Foco e Estrutura Posterior e Inferior",
      "Funções de cada Estrutura do DFMEA",
      "Função matemática do Elemento em Foco",
      "Características de Produto",
      "Conceito de Modo de Falha, Efeito e suas Causas Potenciais",
      "Análise das Tabelas de Severidade, Ocorrência e Detecção para DFMEA",
      "Conceito de Prioridade de Ação associada ao cálculo do Risco",
      "Tabela PA (Prioridade de Ação) e sua interpretação",
      "Ações derivadas da análise da Tabela PA (Otimização)",
      "Diagrama “P” para DFMEA",
      "Diagrama de Blocos",
      "Trabalho em Equipe – Elaboração de DFMEA de um produto da Empresa",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Projeto do Produto/Processo, Engenheiros / Técnicos de Manufatura, Técnicos ligados à Qualidade/Produtividade, Coordenadores de FMEA, Profissionais de Pesquisa e Desenvolvimento de Produto, Green Belts e Black Belts.",
  },
  {
    nome: "PFMEA AIAG-VDA - Análise do Modo e Efeito da Falha de Processo - AIAG-VDA - 1ª Edição",
    desc: [
      "Apresentar conceitos e estrutura de FMEA de Processo, assim como capacitar os colaboradores no entendimento e aplicação eficaz de sua nova interpretação.",
      "A VTB tem assessorado montadoras como Ford, GM, Peugeot, VW e Fiat, assim como seus sistemistas, na elaboração e orientação de FMEA's de Projeto e de Processo. Nos últimos 15 anos a VTB desenvolveu com seus clientes mais de 1.200 FMEA's e revisou outros 550.",
      "Treinamos cerca de 1.800 colaboradores em montadoras e mais de 2.000 nas mais diversas áreas como as do setores médicos, eletrônico, de embalagem, farmacêutico, de alimentos e bebidas, madereiro, metalúrgico, da chamada “linha branca”, de geração de energia, dentre outros.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "08h",
    programa: [
      "Conceitos e Objetivos do FMEA",
      "Evolução histórica do FMEA",
      "Definição de DFMEA e FMEA MSR",
      "O que mudou do FMEA da AIAG 4ª edição para AIAG-VDA 1ª edição",
      "As 07 Etapas de Elaboração de um PFMEA",
      "Construção das Estruturas de um PFMEA",
      "Elemento em Foco e Estrutura Posterior e Inferior",
      "Funções de cada Estrutura do PFMEA",
      "Elemento de Trabalho 4M",
      "Características de Produto",
      "Conceito de Modo de Falha, Efeito e suas Causas Potenciais",
      "Análise das Tabelas de Severidade, Ocorrência e Detecção para DFMEA",
      "Conceito de Prioridade de Ação associada ao cálculo do Risco",
      "Tabela PA (Prioridade de Ação) e sua interpretação",
      "Ações derivadas da análise da Tabela PA (Otimização)",
      "Diagrama “P” para DFMEA",
      "Fluxograma e Plano de Controle vinculados ao PFMEA",
      "Trabalho em Equipe – Elaboração de DFMEA de um produto da Empresa",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Projeto do Produto/Processo, Engenheiros / Técnicos de Manufatura, Técnicos ligados à Qualidade/Produtividade, Coordenadores de FMEA, Profissionais de Pesquisa e Desenvolvimento de Produto, Green Belts e Black Belts.",
  },
  {
    nome: "FMEA - Análise do Modo e Efeito da Falha (4ª Edição)",
    desc: [
      "Apresentar uma Metodologia usada por Equipes responsáveis por Projeto e Manufatura como um meio para assegurar que os modos de falha em potencial e suas causas / mecanismos associados tenham sido considerados e as respectivas ações sejam recomendadas para diminuir ou eliminar a chance de ocorrer estes modos de falha.",
      "A VTB tem assessorado montadoras como Ford, GM, Peugeot, VW e Fiat, assim como seus sistemistas, na elaboração e orientação de FMEA's de Projeto e de Processo. Nos últimos 15 anos a VTB desenvolveu com seus clientes mais de 1.200 FMEA's e revisou outros 550.",
      "Treinamos cerca de 1.800 colaboradores em montadoras e mais de 2.000 nas mais diversas áreas como as do setores médicos, eletrônico, de embalagem, farmacêutico, de alimentos e bebidas, madereiro, metalúrgico, da chamada “linha branca”, de geração de energia, dentre outros.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "16h",
    programa: [
      "Conceito da Metodologia: a FMEA como ferramenta preventiva de antecipação às possíveis falhas",
      "Identificação das funções e requisitos de produtos e processos",
      "Diferenciação conceitual entre modo de falha, causas/mecanismos e efeitos potenciais",
      "Foco preventivo nas origens dos erros e modos de falha",
      "Ferramentas de detecção dos modos de falhas antes do modo de falha chegar ao cliente",
      "Poka Yokes de projeto e de processo",
      "Fault Tree Analysis (FTA): Árvore de falhas",
      "Curva da Banheira: o comportamento da falha através do tempo",
      "Cálculo da ocorrência como função do modo de falha e da causa",
      "Critérios apurados para o cálculo dos índices de ocorrência, detecção e severidade",
      "Análise do Risco (RPN ou NPR) diante do índice de severidade e o impacto no cálculo do Risco Crítico",
      "Deve-se levar ou não em consideração o risco crítico?",
      "Como revisar um FMEA após a tomada de ações?",
      "A tratativa das características críticas/chaves dentro do FMEA",
      "Como comunicar características críticas/chaves do PFMEA para o DMFEA",
      "Exercícios práticos de FMEA de Processo e Projeto",
      "A melhoria contínua aplicadas aos FMEAs como agente de redução do Risco de Falha",
      "Lições Aprendidas e Melhores Práticas",
      "Apresentação do Software <b>WinFMEA</b> - Software de FMEA desenvolvido pela VTB com Banco de Dados e com monitorização inteligente das ações recomendadas",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Projeto do Produto/Processo, Engenheiros / Técnicos de Manufatura, Técnicos ligados à Qualidade/Produtividade, Coordenadores de FMEA, Profissionais de Pesquisa e Desenvolvimento de Produto, Green Belts e Black Belts.",
  },
  {
    nome: "DFMEA 4ª Edição - Análise do Modo e Efeitos de Falha Potencial de Projeto",
    desc: [
      "Apresentar uma Metodologia usada por Equipes responsáveis por Projeto e Manufatura como um meio para assegurar que os modos de falha em potencial e suas causas / mecanismos associados tenham sido considerados e evitados.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "08h",
    programa: [
      "Metodologia FMEA",
      "Etapas de desenvolvimento do DFMEA",
      "<h3>Características do DFMEA de projeto/processo:</h3>",
      "<span>Identificação das funções dos componentes;</span>",
      "<span>Identificação do modo da falha;</span>",
      "<span>Identificação do efeito da falha;</span>",
      "<span>Identificação da causa da falh;a</span>",
      "Diagrama de interações/ Árvore de falhas",
      "Metodologia de controle e validação de projetos/processo",
      "Formas e critérios para determinação dos índices de ocorrência, severidade, detecção e risco",
      "Análise dos índices de risco e sua abordagem no Manual 4ª Edição",
      "Ações corretivas: proposição, viabilização, implantação, acompanhamento",
      "Reavaliação dos índices de risco",
      "Trabalhos práticos sobre o desenvolvimento de um FMEA de Projeto",
      "Apresentação do Software <b>WinFMEA</b> - Software de FMEA desenvolvido pela VTB.",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Projeto do Produto / Processo, Engenheiros / Técnicos de Manufatura, Técnicos ligados à Qualidade / Produtividade.",
  },
  {
    nome: "PFMEA 4ª Edição - Análise do Modo e Efeito da Falha de Processo",
    desc: [
      "Apresentar uma Metodologia usada por Equipes responsáveis por Manufatura como um meio para assegurar que os modos de falha em potencial e suas causas / mecanismos associados tenham sido considerados e evitados.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "08h",
    programa: [
      "Metodologia FMEA",
      "Etapas de desenvolvimento do FMEA de Processo",
      "<h3>Características do FMEA de processo:</h3>",
      "<span>Identificação das etapas do processo;</span>",
      "<span>Identificação dos modos de falhas potenciais;</span>",
      "<span>Identificação dos efeitos potenciais destes modos de falha;</span>",
      "<span>Identificação das possíveis causas destas falhas potenciais;</span>",
      "Metodologia de controle e validação de processo",
      "Função matemática do Elemento em Foco",
      "Formas e critérios para determinação dos índices de ocorrência, severidade, detecção e risco",
      "Análise dos índices de risco e sua abordagem no Manual 4ª Edição",
      "Ações corretivas: proposição, viabilização, implantação e acompanhamento",
      "Reavaliação dos índices de risco",
      "Desenvolvimento de um FMEA de Processo, para cada equipe, focando as condições reais da empresa",
      "Apresentação do Software <b>WinFMEA</b> - Software de FMEA desenvolvido pela VTB",
    ],
    publico:
      "Gerentes, Supervisores, Engenheiros de Processo, Engenheiros / Técnicos de Manufatura, Técnicos ligados à Qualidade / Produtividade.",
  },
  {
    nome: "WEIBULL - Planejamento da Confiabilidade",
    desc: [
      "Fornecer aos participantes ferramentas para analisar o desempenho do produto / processo ao longo do tempo (vida útil), utilizando previsões, testes acelerados e simulações.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "16h",
    programa: [
      "Modelos Probabilisticos",
      "Elementos de Probabilidade e Histograma",
      "Distribuiçõ es usadas em Confiabilidade",
      "Distribuição Normal - Estudo de Papel de Probabilidade Normal",
      "Distribuição de Weibull - Estudo do Papel de Probabilidade Weibull",
      "Análise de Influências de Causas Especiais e Comuns em Distribuições de Probabilidade voltadas para Confiabilidade",
      "Análise da Capabilidade do Processo",
      "Testes Acelerados",
      "Garantia do Produto",
      "Confiabilidade de Sistemas",
      "O enfoque do FMEA do Projeto e Processo dentro da Confiabilidade",
      "<h3>Requisitos para a Especificação da Confiabilidade:</h3>",
      "<span>Técnicas e Aplicações da Análise de Falhas;</span>",
      "<span>Ciclo de Vida do Produto;</span>",
      "<span>Análise da Árvore de Falhas;</span>",
      "Administração da Confiabilidade",
      "WorkShop : implantação de um programa de confiabilidade",
      "Apresentação do <b>WinConf</b> - Software específico para Confiabilidade",
    ],
    publico:
      "Engenheiros ligados a projeto do produto e projeto do processo, técnicos ligados à qualidade e produtividade, gerentes, supervisores, administradores da produção.",
  },
  {
    nome: "QFD - Desdobramento da Função Qualidade",
    desc: [
      "Traduzir em linguagem técnica a Voz, muitas vezes informal, de Clientes de tal forma que ela esteja presente nos desdobramentos das etapas de desenvolvimento do produto e aponte prioridades para a alocação de recursos por parte da alta direção.",
      "Do Inglês “Quality Function Deployment” este método foi aplicado pela primeira vez em 1972 nos estaleiros de Kobe (Japão). Consiste em uma metodologia estruturada matricialmente que ajuda a equipe de desenvolvimento do produto/processo /serviço a traduzir a Voz do Cliente em requisitos técnicos/conceituais em cada etapa desde o estágio inicial de desenvolvimento até ser canalizada em características-chaves de produto, processo ou serviço.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "08h",
    programa: [
      "O porquê do Desdobramento da Função Qualidade e seu enfoque na ISO TS 16949",
      "O Processo QFD voltado para a redução de Lead Time de Projeto",
      "Entendendo, categorizando e Desdobrando a Voz do Cliente",
      "Técnica de Noriaki Kano para modelar o impactos diferentes na Satisfação do Cliente",
      "Analisando novas tecnologias através do Diagrama Conceitual de PUGH",
      "Áreas alocadas em cada etapa de desenvolvimento do produto/serviço",
      "<h3>Como usar o Desdobramento da Função Qualidade para:</h3>",
      "<span>Ouvir a “voz” do Cliente através de pesquisa de mercado;</span>",
      "<span>Avaliar a concorrência através de “Clínicas” de Clientes;</span>",
      "<span>Avaliar a concorrência através de Benchmarking Técnico;</span>",
      "<span>Desenvolver soluções técnicas e estudar os seus eventuais conflitos;</span>",
      "<span>Ponderar o impacto das soluções e priorizá-las para alocar recursos;</span>",
      "Como Planejar a Implantação de um programa QFD",
      "<h3>Desenvolvimento das Fases do Planejamento Avançado da Qualidade do Produto:</h3>",
      "<span>Matriz de Planejamento do Conceito de Produto;</span>",
      "<span>Matriz de Planejamento do Projeto do Produto;</span>",
      "<span>Matriz de Planejamento do Projeto do Processo;</span>",
      "<span>Plano de Controle para Monitoramento da Produção;</span>",
      "Exercícios e Exemplos de Aplicação",
    ],
    publico:
      "Profissionais das áreas de Marketing, Design, Vendas, Comercial, Engenharia, Finanças, Manufatura, PCP, Compras, Qualidade e Assistência Técnica.",
  },
  {
    nome: "DFSS - Projeto para Six Sgima",
    desc: [
      "Capacitar técnicos e engenheiros a criarem projetos de excelência que estejam alinhados à voz do cliente e que possuam alta robustez e confiabilidade.",
    ],
    id: 2,
    tag: "FMEA/Confiabilidade/Projeto",
    tempo: "32h",
    programa: [
      "Conceito de DFSS",
      "Fundamentação na tomada de decisão",
      "DFSS x Improviso técnico",
      "Estratégia IDDOV do DFSS",
      "Como oferecer valor ao cliente",
      "Medidas funcionais",
      "Dados que suportam hipóteses",
      "Seleção de conceitos",
      "Conceito de robustez",
      "Processo de otimização",
      "Pensamento em eficiência",
      "Modelo de Kano",
      "Função perda do cliente",
      "Técnicas de criatividade",
      "Conceito de TRIZ",
      "Tabela de contradição",
      "Função ideal",
      "Diagrama -P",
      "Sinal e fator ruído",
      "Estratégia de fator de controle",
      "Níveis de fatores",
      "Fatores, níveis e combinações",
      "Arranjo ortogonal",
      "Conceito de interações",
      "Predição e confirmação de um experimentos",
      "Fatores de ruídos fracionados",
      "Vários exercícios de aprendizagem",
      "Conceitos e aplicações de DFA",
      "Conceito e aplicação de confiabilidade",
      "Workshop Final - Trabalho em Equipe",
    ],
    publico:
      "Gerentes, supervisores, técnicos, engenheiros, green beltsm black belts, projetistas e coordenadores de projetos.",
  },
  {
    nome: "MASP/8D - Método de Análise e Solução de Problemas",
    desc: [
      "Fornecer diretrizes para resolução de problemas e não conformidades baseadas numa estratégia sistemática composta por 8 etapas segundo o ciclo PDCA, de tal forma a solucionar completamente o problema e aplicar prevenções à sua reocorrência.",
      "O Método de Análise e SOLUÇÃO EFICAZ de Problemas é uma forma estruturada de aplicação das diversas ferramentas da qualidade, e outras mais complexas, focada na identificação, correção e prevenção de causas de falhas e não conformidades.",
      "O uso correto destas ferramentas, através de trabalho de equipe eficaz, busca fazer uma análise mais científica dos processos, e propor soluções mais rápidas e eficazes, baseadas em evidências de causa(s) raiz(es) profundamente estudadas.",
    ],
    id: 2,
    tag: "Melhoria Contínua",
    tempo: "16h",
    programa: [
      "<h3>1ª Fase - Formação das Equipes para Solução Eficaz de Problemas (SEP) (8D):</h3>",
      "<span>Processo Estruturado para Resolução de Problemas;</span>",
      "<span>Formar uma equipe multifuncional condizente com o problema;</span>",
      "<span>Descrever minuciosamente o problema;</span>",
      "<span>Implementar ações de contenção;</span>",
      "<span>Identificar todas as causas raízes;</span>",
      "<span>Avaliar alternativas de solução eficaz de problemas;</span>",
      "<span>Implementar ações corretivas;</span>",
      "<span>Implementar prevenção completa da causa raiz;</span>",
      "<span>Projeto Robusto;</span>",
      "<span>Realizar abordagem para problemas e processos similares;</span>",
      "<span>Uso de Check List para cada etapa de resolução;</span>",
      "<span>Lições Aprendidas;</span>",
      "<h3>2ª Fase - Ferramentas de Suporte à Solução de Problemas:</h3>",
      "<span>Ciclo PDCA;</span>",
      "<span>As 07 Ferramentas Clássicas da Qualidade;</span>",
      "<span>Ferramentas para Solução de Problemas Complexos;</span>",
      "<span>Aplicação Eficaz do Diagrama de Ishikawa;</span>",
      "<h3>3ª Fase - Workshop de Aplicação:</h3>",
      "<span>Trabalho em equipe focando um problema real da empresa;</span>",
      "<span>Formulário VTB para a Resolução de Não-Conformidade;</span>",
      "<h3>4ª Fase - Dicas de como implantar MASP na sua Empresa:</h3>",
      "<span>Como envolver a Liderança na implementação da metodologia;</span>",
      "<span>Como praticar a melhoria contínua como atitude normal do dia a dia;</span>",
      "<span>Importância de investir na metodologia;</span>",
      "<span>Principais benefícios da metodologia;</span>",
    ],
    publico:
      "Gerentes, supervisores, líderes de equipe, coordenadores, engenheiros, técnicos ligado à qualidade e produtividade, green belts e black belts.",
  },
  {
    nome: "Qualificação e Desenvolvimento de Fornecedores",
    desc: [
      "Atender às recomendações da Norma ISO 9001:2008 e Especificação Técnica ISO/TS 16949 no que se refere ao asseguramento da qualidade de fornecimento.",
    ],
    id: 45,
    tag: "Melhoria Contínua",
    tempo: "16h",
    programa: [
      "<h3>Objetivos de um Programa de Auditoria:</h3>",
      "<span>Classificação das Auditorias;</span>",
      "<h3>Item 7.4 da ISO 9001:2008 e ISO /TS 16949:</h3>",
      "<span>Processo de Aquisição;</span>",
      "<span>Desenvolvimento do Sistema da qualidade dos fornecedores;</span>",
      "<span>Terceiros aprovados pelo cliente;</span>",
      "<span>Informações de aquisição;</span>",
      "<h3>Verificação do produto adquirido:</h3>",
      "<span>Qualidade dos produtos recebidos;</span>",
      "<span>Acompanhamento / Monitoramento dos fornecedores;</span>",
      "<h3>Auditoria de segunda parte</h3>",
      "<h3>Workshop de aplicação</h3>",
    ],
    publico:
      "Engenheiros, Técnicos e especialistas das áreas de Qualidade Aquisição.",
  },
  {
    nome: "5S's - Housekeeping",
    desc: [
      "Filosofia originalmente criada no Japão em meio de 1950 pelo Centro de Educação para a Qualidade, liderado pelo Dr. Kaoru Ishikawa e seus colegas.",
      "Foca a necessidade de manter em ordem e limpo o local trabalho propiciando um ambiente agradável para se trabalhar sem que haja perda de tempo para se achar as coisas, buscando a higienização e assim evitar doenças, a ergonomia que lesa o trabalhador e a própria empresa. Para que isto ocorra deve-se implementar e praticar todos os 5s desde o descarte de coisas supérfluas até a disciplina por parte de todos os colaboradores.",
      "Aumentar a eficiência do local de trabalho através da eliminação do desperdício e da criação de um ambiente limpo, com higiene e agradável para se trabalhar, maximizando assim os índices de qualidade, segurança e produtividade de cada atividade",
    ],
    id: 45,
    tag: "Melhoria Contínua",
    tempo: "8h",
    programa: [
      "<h3>Fundamentos do Housekeeping / 5S's</h3>",
      "<h3>5 S's, o ponto de partida para Implementação de Programas da QUALIDADE / PRODUTIVIDADE</h3>",
      "<h3>Atividades Sequenciais do 5S's</h3>",
      "<h3>SEIRI - Organização SEITON - Ordem SEISO - Limpeza</h3>",
      "<h3>SEIKETSU - Asseio SHITSUKE - Disciplina</h3>",
      "<h3>Utilização do 5S's na Implementação de Melhoria Contínua</h3>",
      "<h3>Identificação de oportunidades para a Implementação de Projetos de Melhoria da Qualidade e Produtividade</h3>",
      "<h3>Técnicas para Melhoria Contínua</h3>",
      "<h3>Instalações, Equipamento, Planejamento de Pessoal, Eficiência</h3>",
      "<h3>Abordagem a prova de falhas (POKA YOKE)</h3>",
      "<h3>Gerenciamento do Ferramental:</h3>",
      "<span>Prevenção versus Detecção;</span>",
      "<h3>Ênfase em prevenção</h3>",
      "<h3>Ciclo de Melhoria Contínua de Processo - PDCA</h3>",
      "<h3>Técnicas para iniciar a filosofia do Housekeeping / 5S's</h3>",
      "<h3>Processo SOL (Segurança, Ordem e Limpeza)</h3>",
      "<h3>Comissão permanente de avaliação</h3>",
      "<h3>Como programar um dia para a “GRANDE LIMPEZA”</h3>",
      "<h3>Check-list para verificação dos 5S's</h3>",
      "<h3>Envolvimento de todos para manter o Housekeeping</h3>",
      "<h3>Housekeeping como método para otimizar questões relacionadas a saúde, segurança e meio ambiente</h3>",
      "<h3>Conservação dos equipamentos: um passo para a Manutenção Produtiva Total - TPM</h3>",
      "<h3>Reconhecimento das pessoas</h3>",
      "<h3>Programa de Implantação, Monitoramento e Manutenção do 5S's:</h3>",
      "<span>Mobilização;</span>",
      "<span>Promoção;</span>",
      "<span>Educação;</span>",
      "<h3>Os 5S's no escritório</h3>",
      "<h3>Aplicações Práticas</h3>",
    ],
    publico:
      "Todos os funcionários de pequenas, médias e grandes empresas, tanto de área manufatureira como de área administrativa.",
  },
  {
    nome: "Gestão pela Qualidade",
    desc: [
      "Melhorar contínuamente a produtividade em cada nível de operação e em cada área funcional de uma organização, utilizando todos os recursos financeiros e humanos disponíveis.",
    ],
    id: 45,
    tag: "Melhoria Contínua",
    tempo: "16h",
    programa: [
      "<h3>Organização com Enfoque na Qualidade Total:</h3>",
      "<span>Conceito de produto, cliente e qualidade;</span>",
      "<span>Princípios da Qualidade Total;</span>",
      "<span>Roteiro para o Planejamento da Qualidade Total;</span>",
      "<span>Gerenciamento da Qualidade: definição, necessidade;</span>",
      "<span>A trilogia da Qualidade: Planejamento, Controle e Aperfeiçoamento;</span>",
      "<span>Administração da Qualidade Total: propósitos, organização;</span>",
      "<span>Competitividade através da Qualidade Total: voz do mercado, voz da organização, voz dos processos;</span>",
      "<span>Conceito de produto, cliente e qualidade;</span>",
      "<span>Ciclo PDCA;</span>",
      "<span>Ferramentas para a Qualidade;</span>",
      "<h3>Gerenciamento da Qualidade:</h3>",
      "<span>Elementos fundamentais: visão organizacional, diretrizes gerais, prioridades corporativas, hipóteses de base, análise do sistema organizacional;</span>",
      "<span>Participação dos níveis operacionais da empresa;</span>",
      "<span>Relacionamento com os fornecedores externos;</span>",
      "<span>Relacionamento cliente/ fornecedor interno;</span>",
      "<span>Equipe multifuncional: uma ferramenta de produtividade e qualidade;</span>",
      "<span>Implementação das ações corretivas e preventivas;</span>",
      "<h3>Gerenciamento da Mudança:</h3>",
      "<span>Cultura corporativa;</span>",
      "<span>Participação dos níveis operacionais da empresa;</span>",
      "<span>Cultura na área operacional;</span>",
      "<span>Conhecimento tácito versus conhecimento explícito;</span>",
      "<span>Auto controle;</span>",
      "<span>Processo decisório e criativo em grupo;</span>",
    ],
    publico:
      "Diretores, Gerentes, Chefias, Supervisores, Técnicos, Analistas e Administradores.",
  },
  {
    nome: "PDCA - Ciclo de Melhoria Contínua",
    desc: [
      "Apresentar o PDCA como um mecanismo estratégico, baseado em um ciclo de desenvolvimento de diretrizes gerenciais com foco em melhoria contínua, promovendo assim, o rompimento da situação atual para se atingir os resultados e metas necessárias na busca da sustentabilidade da organização.",
    ],
    id: 45,
    tag: "Melhoria Contínua",
    tempo: "08h",
    programa: [
      "<p>Conceito de ciclo PDCA</p>",
      "<p>Mapeamento do Processo</p>",
      "<h3>As fases do PDCA:</h3>",
      "<span><b>P</b>: Planejamento com definição dos objetivos e estratégias e recursos necessários para atingi-los;</span>",
      "<span><b>D</b>: Execução das tarefas descritas no Plano Estratégico para atingimentos dos objetivos a serem alcançados;</span>",
      "<span><b>C</b>: Verificação análise dos resultados das atividades executadas como Input às ações recomendadas para cumprimento do Plano Estratégico;</span>",
      "<span><b>A</b>: Conjunto de ações necessárias para a manutenção, correção ou melhoria contínua do Sistema de Gestão pertinente à realização de objetivos pré-estabelecidos;</span>",
      "<h3>Ferramentas da Qualidade disponíveis como forma de integração às fases do ciclo PDCA:</h3>",
      "<span><b>Fluxograma</b>: ajuda no mapeamento do processe;</span>",
      "<span><b>Espinha-de-Peixe (Ishikawa)</b>: busca das causas-raízes de problemas;</span>",
      "<span><b>5 Porquês</b>: técnica de aprofundamento na busca das causas fundamentais de não-conformidades;</span>",
      "<span><b>Diagrama de Verificação</b>: contabilização de atributos atrelados às características críticas;</span>",
      "<span><b>Gráfico de Pareto</b>: priorização das causas e problemas fundamentais de um sistema;</span>",
      "<span><b>Histograma</b>: quantificação e modelamento na distribuição de dados coletados;</span>",
      "<span><b>Gráfico de Controle</b>: Análise da estabilidade de pontos vitais de um processo;</span>",
      "<span><b>5W2H</b>: ferramenta de planejamento na tomada de ações corretivas e preventivas;</span>",
      "<p>Workshop de Aplicação</p>",
    ],
    publico:
      "Gerentes e supervisores de sistemas de gestão, líderes e coordenadores de desenvolvimento de novos projetos e produtos, Black Belts e facilitadores de programas de melhoria contínua.",
  },
  {
    nome: "As 7 Ferramentas da Qualidade",
    desc: [
      "Familiarizar os participantes com técnicas de estatística descritiva que permitem a análise, coleta, processamento e disponibilização de informações sobre a variação do processo.",
    ],
    id: 45,
    tag: "Melhoria Contínua",
    tempo: "08h",
    programa: [
      "<p>Estatística descritiva</p>",
      "<p>Conceitos de Ferramentas da Qualidade</p>",
      "<p>Ciclo PDCA</p>",
      "<h3>As 7 Ferramentas:</h3>",
      "<span>Fluxograma;</span>",
      "<span>Checklist / 5W – 2H;</span>",
      "<span>Histograma;</span>",
      "<span>Diagrama de Ishikawa;</span>",
      "<span>Diagrama de Pareto;</span>",
      "<span>Diagrama de Correlação;</span>",
      "<span>Cartas de Controle;</span>",
      "<p>Exercícios de Aplicação</p>",
    ],
    publico:
      "Profissionais da área da qualidade e processos produtivos. Gerentes, Diretores e Técnicos do Processo.",
  },
  {
    nome: "Plano de Controle",
    desc: [
      "Habilitar os participantes na elaboração e interpretação do Plano de Controle com base nos requisitos do APQP - Planejamento Avançado da Qualidade do Produto do Setor Automotivo.",
    ],
    id: 45,
    tag: "Manufatura",
    tempo: "08h",
    programa: [
      "<p>Importância do Plano de Controle na IATF 16949:2016</p>",
      "<h3>Plano de Controle como parte integrante do APQP:</h3>",
      "<span>Planejamento;</span>",
      "<span>Desenvolvimento;</span>",
      "<span>Verificação;</span>",
      "<span>Validação;</span>",
      "<span>Retroalimentação e Ação Corretiva</span>",
      "<span>Plano de Controle;</span>",
      "<h3>Ferramentas para o desenvolvimento de um Plano de Controle:</h3>",
      "<span>Ciclo PDCA;</span>",
      "<span>Fluxograma;</span>",
      "<span>FMEA, MSA e CEP;</span>",
      "<p>Lições Aprendidas</p>",
      "<p>Análise Crítica do Plano de Controle</p>",
      "<p>WORKSHOP DE APLICAÇÃO</p>",
    ],
    publico:
      "Profissionais interessados em desenvolvimento, implementação e documentação para o monitoramento do Produto/Processo. Auditores Internos da ISO 9001:2015 e IATF 16949:2016.",
  },
  {
    nome: "CORE TOOLS – Ferramentas da Qualidades Automotiva - Implantação",
    desc: [
      "Preparar os participantes para Implementação e Auditoria Interna das ferramentas da qualidade automotiva: FMEA, CEP, MSA APQP, PPAP e MASP – 8D.",
    ],
    id: 45,
    tag: "Manufatura",
    tempo: "16h",
    programa: [
      "<p>Abordagem de Processos na Implementação de Core Tools e Gestão de Riscos</p>",
      "<p>Seqüência lógica e eficaz na implementação de Core Tools e Ciclo PDCA</p>",
      "<h3>Revisão das Core Tools e sua correlação com a IATF 16949:2016:</h3>",
      "<span>FMEA;</span>",
      "<span>CEP;</span>",
      "<span>MSA;</span>",
      "<span>APQP / PPAP;</span>",
      "<span>MASP/8D;</span>",
      "<p>Metodologia de Auditoria Interna nas Core Tools</p>",
      "<p>Workshop de Implantação das Core Tools baseado em Trabalho de Equipe.</p>",
    ],
    publico:
      "Diretores, gerentes, engenheiros de produto e processo, Administradores da Produção, Técnicos ligados à qualidade e produtividade. Auditores Internos da IATF 16949:2016 ligados a processos de manufatura da organização e dos fornecedores.",
  },
];
